### ISSUE TITLE
Days not visible on Firefox

### ISSUE THREAD

**Issue by XaviAlsina** [Paul-DS/bootstrap-year-calendar#1]
The days are not visible on Firefox 42.0 (Yosemite 10.10)

![captura de pantalla 2015-11-26 a las 8 50 46](https://cloud.githubusercontent.com/assets/4067381/11417940/64c46382-941b-11e5-803a-9973e0542ec9.png)

**Comment by Paul-DS** [comment]
Fixed in commit 8540198. Thanks for testing.
