### ISSUE TITLE
StartDate and EndDate on Calendar

### ISSUE THREAD

**Issue by 360noscope** [Paul-DS/bootstrap-year-calendar#100]
Ok i can figure out how to let them work with modal now. When i enable range date selection i can't using
`e.dateStart.toLocaleString()` or `e.dateEnd.toLocaleString()` to get start or end date did i miss something :)

This is part that i testing to see start date of range selection
```
$('#calendar').clickDay(function(e) {
	alert(e.startDate.toLocaleDateString());
});
```

And this is part where i enable range selection

```
$(function() {
	$('#calendar').data('calendar').setEnableRangeSelection(true);

});
```

**Comment by Paul-DS** [comment]
Hi,

You should use the **selectRange** event instead of the clickDay event.
See in the [documentation](http://www.bootstrap-year-calendar.com/#Documentation/Events)
