### ISSUE TITLE
Hiding months?

### ISSUE THREAD

**Issue by tatanij** [Paul-DS/bootstrap-year-calendar#101]
Hi I'm looking to only have 3 months display within the current month. I'm quite new to bootstrap and was wondering if this is possible ?

**Comment by starkeins** [comment]
+ same here

**Comment by William-H-M** [comment]
Maybe something like this can help #18

**Comment by pdarkness** [comment]
I used #18 as base for doing the same thing using the renderEnd function.

` $('#calendar').calendar({
            renderEnd: function (e) {
            var currentMonth = new Date().getMonth();
            $('#calendar .month-container').each(function (idx, el) {
                if (idx < currentMonth) {
                    $(this).css("display", "none");
                }
                if (idx > currentMonth + 2) {
                    $(this).css("display", "none");
                }
            });
        }
    });
`

**Comment by Paul-DS** [comment]
I know this thread is pretty old, but I'm working on this feature in the new version of the library: [js-year-calendar](https://github.com/year-calendar/js-year-calendar)
You can follow the development (and test the functionality) in the PR year-calendar/js-year-calendar#32

**Comment by Paul-DS** [comment]
The feature is available in js-year-calendar@v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
