### ISSUE TITLE
function(e) get "e.id" not working

### ISSUE THREAD

**Issue by SteveRabbit** [Paul-DS/bootstrap-year-calendar#102]
Hi, my datasource has the structure:
[ {   id:  1,
    name:  todo,
    startDate:   xxxxx,,
    endDate:  xxxx  } ]
When I use "dayClick: function(e) { alert( "Event ID = " + e.id ) } " I want to get the ID of the event.
BUT  I always get "Event ID = undefined " .... 
How can I get the ID of the underlaying Event ??

**Comment by Paul-DS** [comment]
Hi,

There is few errors in your code:
- The event name is **clickDay**, not dayClick
- The event parameter is an object that contain several properties, including the list of events. So if your param is named `e`, you can use the following code to get the id `alert(e.events[0].id)` (if you are sure about the number of events on this day)

Moreover, I introduced a bug yesterday concerning the computation of the event parameters, which I fixed this morning (commit 8ab60d22bab8048ca62f5fbaad14ec2c3fdf640b), so if you took the last GitHub version yesterday, update the calendar code).

**Comment by SteveRabbit** [comment]
Thank you very much, it works now ! ;-)
