### ISSUE TITLE
Affichage d'une période sélectionnée

### ISSUE THREAD

**Issue by jamal1989** [Paul-DS/bootstrap-year-calendar#11]
il y a un petit problème concernant sa  quand je sélectionne une period l'affichage est sur le mois prochain   
par exemple date début est 2016-10-12 et date fin  est 2016-10-21
affichage sur l'agenda et  2016-11-12 et date fin  est 2016-11-21
merci pour le plugine

**Comment by Paul-DS** [comment]
Si je comprends bien ton problème, lorsque tu essaye d'afficher une période sur le mois 10, celle-ci s'affiche sur le mois de novembre ?

Si c'est bien ça, ce n'est pas un problème. En javascript, le mois de l'objet Date va de 0 (janvier) à 11 (décembre).

Documentation : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

> **month**
> Integer value representing the month, beginning with 0 for January to 11 for December.

Dis-moi si ça ne correspond pas à ton problème !

**Comment by jamal1989** [comment]
merci

**Comment by jamal1989** [comment]
bonjour 
comment faire pour modifier le format de la date ? et la sélection ne se fait pas sur les date passé 
comment je peux désactiver toutes une période au lieux de désactiver jour par jour 

merci  
cordialement jamal

**Comment by Paul-DS** [comment]
> comment faire pour modifier le format de la date ?

Quel format exactement veux-tu modifier ?

-

> la sélection ne se fait pas sur les date passé

Je ne comprends pas trop, peux-tu détailler un peu plus ?

-

> comment je peux désactiver toutes une période au lieux de désactiver jour par jour

Ce n'est pas possible pour le moment. Je vais voir pour implémenter ça dans la prochaine version (si ça ne nuit pas trop aux performances).

**Comment by jamal1989** [comment]
bah pour la date j'ai eu comment faire la modification  

c'est e logique de créer un événement dans une période passer

merci

**Comment by Paul-DS** [comment]
Oui effectivement, mais le plugin le permet actuellement.

Dans le premier exemple du site, j'ai créé 2 evenements en février 2013, et cela fonctionne très bien :
![image](https://cloud.githubusercontent.com/assets/15329946/13555931/d35aeeae-e3cd-11e5-8a33-3e3f5bd057d4.png)

**Comment by jamal1989** [comment]
bonjour
 est ce que je peux affecter un couleur prédéfini  pour chaque événement ?  .
jad 
merci

**Comment by Paul-DS** [comment]
Oui, tu peux définir une couleur pour chaque élément de ton data source, en utilisant la propriété `color`:

```
$('#calendar').calendar({ 
    dataSource: [
        {
            startDate: new Date(2016, 1, 4),
			endDate: new Date(2016, 1, 15),
			color:'red'
		},
		{
			startDate: new Date(2016, 3, 5),
			endDate: new Date(2016, 5, 15),
			color:'#FFFF00'
		}
	]
});
```

**Comment by jamal1989** [comment]
merci infiniment
