### ISSUE TITLE
Options [ minDate ] and [ maxDate ] are not working.

### ISSUE THREAD

**Issue by funcion** [Paul-DS/bootstrap-year-calendar#112]
Good day,

I am trying to apply options available in this section http://www.bootstrap-year-calendar.com/#Documentation/Options but these options seems not to be working, the idea is to avoid showing years older or younger than the established ones, I leave the example code working, to see if they can help me.

EJ: https://jsfiddle.net/milindex/ucem1ds1/1/ 

**1) I have made it work as follows:**

`minDate: new Date(currentYear, 2, 1)`

**2) But I would like to know why it is not working in these ways:**

`minDate: new Date('01/01/2017'),`

`$('#calendar').data('calendar').setMaxDate('02/31/2017');`

I would greatly appreciate your help.

_Thank you very much._

**Comment by William-H-M** [comment]
Hi, the 2 option you setted, if not wrong, it should get a date parameter and not an option parameter I made a [fiddle ](https://jsfiddle.net/ucem1ds1/2/)and it does works for me with the
```
minDate: new Date('01/01/2017'),
$('#calendar').data('calendar').setMaxDate('02/31/2017');
```

**Comment by funcion** [comment]
Perfect, thank you very much William-H-M, it's working now.

**Comment by William-H-M** [comment]
As this is solved please close this issue that way people will check faster for this
