### ISSUE TITLE
Calendar height appears squeezed in Chrome

### ISSUE THREAD

**Issue by daizylogik** [Paul-DS/bootstrap-year-calendar#116]
I am just displaying a simple calendar, without any options. It appears correctly in Firefox, but the height is squeezed in Chrome, and some dates overlap. Has anyone else had this issue?
<img width="1410" alt="chrome" src="https://cloud.githubusercontent.com/assets/11565277/24520010/bcd1f4de-153b-11e7-9803-ccf199e6c0ae.png">

**Comment by William-H-M** [comment]
Did you solve this problem?, I would like to know how

**Comment by daizylogik** [comment]
Yes, it was my fault - by browser was zoomed out too much.
