### ISSUE TITLE
Support installation via Bower or NPM

### ISSUE THREAD

**Issue by gbespyatykh** [Paul-DS/bootstrap-year-calendar#12]
I think, that ability to install this great calendar via JS package managers is very necessary.

**Comment by Paul-DS** [comment]
Ok, thank you for your recommendation, I will take a look !

**Comment by eldiddio** [comment]
+1 to this, the ability to be able to pull this in via npm would greatly help.

At the moment I have just downloaded the files and included them with browsify.

Thanks

**Comment by Paul-DS** [comment]
I published packages for the plugin in Bower and NPM. Please let me know if you see some issues, this is the first time I do it.

**Comment by anshbansal** [comment]
@Paul-DS 
It would be great if the installation instructions from bower/npm are present in the README.

**Comment by kipergil** [comment]
Bower installation has an error while installing...
Could you please check that again ? 
This is the error message : 
`
bower bootstrap-year-calendar#*          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/Paul-DS/bootstrap-year-calendar.git", exit code of #3221225504`
