### ISSUE TITLE
Show 6 months from the current month in a single line

### ISSUE THREAD

**Issue by funcion** [Paul-DS/bootstrap-year-calendar#120]
I need to show the following 6 months from the current month, and that these 6 months are shown in a single line, and that the months before the current month do not appear.

I would greatly appreciate your help.

**Comment by William-H-M** [comment]
Hi, you can do it with samples show on
#18 
#101

**Comment by Paul-DS** [comment]
I know this thread is pretty old, but I'm working on this feature in the new version of the library: [js-year-calendar](https://github.com/year-calendar/js-year-calendar)
You can follow the development (and test the functionality) in the PR year-calendar/js-year-calendar#32

**Comment by Paul-DS** [comment]
The feature is available in js-year-calendar@v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
