### ISSUE TITLE
Chinese translation for calendar

### ISSUE THREAD

**Issue by Linbubin** [Paul-DS/bootstrap-year-calendar#122]
Dear Paul, I want to use languages for chinese,but I can't find this file.
you can look [this](https://github.com/uxsolutions/bootstrap-datepicker/blob/b92ba211ff302d4a4a3436f01201d96d8c96c312/js/locales/bootstrap-datepicker.zh-CN.js).
I'm not sure What is needed to add, but I hope you can submit it earlier, thanks.

**Comment by William-H-M** [comment]
Hi, I've made a [PR](https://github.com/Paul-DS/bootstrap-year-calendar/pull/124) please check it out, to see if a get wrong on something

**Comment by Linbubin** [comment]
all right， thanks
