### ISSUE TITLE
Remove year  on head

### ISSUE THREAD

**Issue by Linbubin** [Paul-DS/bootstrap-year-calendar#123]
I just want to display month and day this year. 
so can be set to make the year not displayed on the page？

**Comment by William-H-M** [comment]
Hi, you can do this quite easy with setting 2 options minDate and maxDate, that way just the current year will be display, just do it like this

minDate: new Date('01/01/2017'),
maxDate new Date('12/31/2017')

here's a [quick example](https://jsfiddle.net/vmae6dfg/)

**Comment by Linbubin** [comment]
@William-H-M    it work :+1:    thanks。
but the code you lose a `:`
```
minDate: new Date('01/01/2017'),
maxDate: new Date('12/31/2017')
```
