### ISSUE TITLE
Clicking next / prev jumps up page

### ISSUE THREAD

**Issue by eldiddio** [Paul-DS/bootstrap-year-calendar#13]
I have the calendar at the bottom of a long page, when you click next / previous buttons it moves the view point further up the page and the calendar is no longer visible without scrolling back down.

Thanks for the great plugin!

**Comment by Paul-DS** [comment]
This is now fixed !

Sorry for the wait.

**Comment by eldiddio** [comment]
Works perfectly, Thanks!
