### ISSUE TITLE
how to use "customDayRenderer"

### ISSUE THREAD

**Issue by Linbubin** [Paul-DS/bootstrap-year-calendar#134]
who can give me a full html about "customDayRenderer".

I don't understand how to use it.
anyway, thanks :)

I want to make "dataSource" looks like disabled day(but dataSource still can display location and update or delete event).
I use ` setTimeout(function(){$('td[style^="box-shadow"]').addClass('disabled').css('box-shadow','')},100);`.
but when i change year, it Invalid.
so i want to know how to make dataSource look like "disabled" forever。

**Comment by William-H-M** [comment]
Hi, you can do it like this
```
customDayRenderer: function(element, date) {
       $(element).addClass('disabled');
 //where element it's each day and you still can see the events
        }
```

**Comment by Linbubin** [comment]
@William-H-M  sorry, I don't know where add this code.
Can you help me revise [this](https://github.com/Linbubin/Hello-world/blob/master/a.html),and push it?

Or help me find a full page。 
anyway , thanks!

**Comment by William-H-M** [comment]
Hi, after some try I saw that if using the way I told you it won't work as is not applying to the container so the logic will actually be:

```
customDayRenderer: function(element, date) {
       $(element).parent().addClass('disabled');
        }
```

But thios will cause some bug that doesn't show the events as is need it, so I just solved in the easy way just add this in the buttom of your script

```
  $( document ).ready(function() {
    setTimeout(function(){ $(".day").addClass('disabled'); }, 0);
    });
```

This will make what you want.

BTW: For what exactly you want this? if you just don't want to create events you can just remove the part of createEvent

**Comment by Linbubin** [comment]
@William-H-M  I want to use all the events in [full example]()
include(create, update, delete).

but i don't know how to show the DataSource looks like disable,
so I add 

`setTimeout(function(){$('td[style^="box-shadow"]').addClass('disabled').css('box-shadow','')},100);`

every events function.

but when I switch to another year, it won't work.

if I use your code:

```
  $( document ).ready(function() {
    setTimeout(function(){ $(".day").addClass('disabled'); }, 0);
    });
```

it make all page looks like "disabled",
but  I want to make "DataSource" looks like "disabled",(for example, remove underline and add class="disabled") 
and I want this effect still works when I switch the year.

Do I need to make myself clear?
Can you help me add some JS to achieve this effect？

**Comment by Linbubin** [comment]
@William-H-M   
hi， I found a way, but it looked a little stupid，just add

```
yearChanged: function(e){
           setTimeout(function(){$('td[style^="box-shadow"]').addClass('disabled').css('box-shadow','')},100);
           }
```

when I switch year, i work well!
