### ISSUE TITLE
how add a event or make a date.. examle me brithday

### ISSUE THREAD

**Issue by OmarBethelRan** [Paul-DS/bootstrap-year-calendar#136]
excuse me I have a problen when I try make a event, I can show the calendar in the web site it is good, but when I try of add or make a event  it don't work. only when I click in a number of day and it put great  and not hapen noting... pleas help me..

**Comment by William-H-M** [comment]
Hi, when you do it does it print an error on the console of the browser or something like that? and what do you mean by "try of add or make a event it don't work"?

**Comment by OmarBethelRan** [comment]
ok, thanks for answer, 
in the DEMO here: http://www.bootstrap-year-calendar.com/#Examples/Full example
you can click in a spesific day, and make your self event like a diary. and I can't do it.
for example I have a interview in september 16, when I click in september 16 in my calendar nothing happens.... not show the window for make the event...... in my web site...

**Comment by William-H-M** [comment]
Ohhh I know what you mean now, doesn't appear the modal window as on the example, I've set up a little example on a past issue just follow what it's included, basically ypur problem is that you don't neither a modal, nor the datepicker plugin.

Reference to this #129 and #117, on 117 you can just copy and paste my code and that's it.

You can download this basic [template ](https://github.com/William-H-M/Hello-world)I made a while ago

**Comment by OmarBethelRan** [comment]
excuseme... but it's not in automatic? ... the code work but maked the event in the code, 
I thought that it was automaticly....

**Comment by OmarBethelRan** [comment]
ok, thanks for answer, 
in the DEMO here: http://www.bootstrap-year-calendar.com/#Examples/Full example
you can click in a spesific day, and make your self event like a diary. and I can't do it.
![untitled](https://cloud.githubusercontent.com/assets/19978027/25861022/1fa11400-34a9-11e7-9d32-25070f0da0a4.png)
![untitled2](https://cloud.githubusercontent.com/assets/19978027/25861023/1fa24028-34a9-11e7-8b2a-2edda24b6ccc.png)


for example I have a interview in september 16, when I click in september 16 in my calendar nothing happens.... not show the window for make the event......

in the images I make calendario.PHP that it have the calendar,   and  I show it in principal menu... but somthing missing for the windows modal and make a event....... 
thanks for helpp me...

**Comment by OmarBethelRan** [comment]
thank you William-H-M the code work... copile and add a event ..... I have a dude is normal that when refresh the page or close and open it, the event maked desapear,  so I have to make other event similar?
or the event have to be saved and apear it doesn't metter if close the page or refresh

**Comment by William-H-M** [comment]
Hi, the reason because disappears is because the datasource I gave on my example, and on the page is just temporal, the only way that they still appear is if you have a Database and the datasource is filled with the info from the database, there's a lot of ways to do it but depends mainly from the language code that you're programming

**Comment by OmarBethelRan** [comment]
thank you so much William-H-M,   for helpp me, and for dedicate time in answere the questions... thanks
