### ISSUE TITLE
is it possible hide already passed months?

### ISSUE THREAD

**Issue by korkuttaha** [Paul-DS/bootstrap-year-calendar#146]
Hello,

There is disable days option but is it possible to hide fully passed months aswell?

Best wishes

**Comment by William-H-M** [comment]
Hi, please refer to 
#18 
#101 

This can be closed as the examples there do what the issue is about it.

**Comment by korkuttaha** [comment]
Thanks, with this code, its working.

renderEnd: function (e) { var currentMonth = new Date().getMonth(); $('#calendar .month-container').each(function (idx, el) { if (idx < currentMonth) { $(this).css("display", "none"); } if (idx > currentMonth + 12) { $(this).css("display", "none"); } });   },
