### ISSUE TITLE
min-date

### ISSUE THREAD

**Issue by korkuttaha** [Paul-DS/bootstrap-year-calendar#148]
Hello,

My calendar working with this code but i would like to set min-date for it. How can i implent mindate into this code?
`
  <script type="text/javascript">
$(function() {
    var currentYear = new Date().getFullYear();

    $('#calendar').calendar({
	
        enableContextMenu: false,
renderEnd: function (e) { var currentMonth = new Date().getMonth(); $('#calendar .month-container').each(function (idx, el) { if (idx < currentMonth) { $(this).css("display", "none"); } if (idx > currentMonth + 12) { $(this).css("display", "none"); } });   },

        disabledDays: [
		 
            new Date(currentYear,6,7),
            new Date(currentYear,6,8),
            new Date(currentYear,6,9),
            new Date(currentYear,6,10),
            new Date(currentYear,6,11),
            new Date(currentYear,6,12),
            new Date(currentYear,6,13),
            new Date(currentYear,6,26),
            new Date(currentYear,6,27),
            new Date(currentYear,6,28),
            new Date(currentYear,6,29),
            new Date(currentYear,6,30),
            new Date(currentYear,7,1),
            new Date(currentYear,7,2),
            new Date(currentYear,7,3),
            new Date(currentYear,7,4),
            new Date(currentYear,7,5),
            new Date(currentYear,7,6),
            new Date(currentYear,7,7),
            new Date(currentYear,7,8),
            new Date(currentYear,7,17),
            new Date(currentYear,7,18),
            new Date(currentYear,7,19),
            new Date(currentYear,7,20),
            new Date(currentYear,7,21),
            new Date(currentYear,7,22),
            new Date(currentYear,7,23),
            new Date(currentYear,7,24),
            new Date(currentYear,7,25),
            new Date(currentYear,7,26),
            new Date(currentYear,7,27),
            new Date(currentYear,7,28),
            new Date(currentYear,8,14),
            new Date(currentYear,8,15),
            new Date(currentYear,8,16),
            new Date(currentYear,8,17),
            new Date(currentYear,8,18),
            new Date(currentYear,8,19),
            new Date(currentYear,8,20)
        ]
    });

});
</script>
`
Thanks in advance

**Comment by William-H-M** [comment]
Hi, you just need to set up the option [minDate](http://www.bootstrap-year-calendar.com/#Documentation/Options)
like minDate:  new Date(currentYear,8,19)

**Comment by korkuttaha** [comment]
Thanks alot for help and fast answers

best wishes
