### ISSUE TITLE
initiating two calendars for two divs

### ISSUE THREAD

**Issue by bardiaheshmati** [Paul-DS/bootstrap-year-calendar#15]
I have initiated calendar for two different divs with two different class names with different MaxDate but upon adding the calendar to the div the other calendar also gets affected. for the moment i managed to fix this issue by destroying and creating calendar every time i want to use it. which is a bit inefficient . any suggestions !?

i also tried setting the max date by setMaxDate() but doesn't work

**Comment by Paul-DS** [comment]
I created a simple example with your case, and it seems to work as expected : http://www.bootstrap-year-calendar.com/test_bardiaheshmati/

Did I miss something ?
