### ISSUE TITLE
getting event.id for deleting and updating existing events

### ISSUE THREAD

**Issue by echeng924** [Paul-DS/bootstrap-year-calendar#151]
Using the function below I pulled from the full example,  when editEvent triggers I'm not getting an event.id.  In trying to debug this I console logged event and I'm seeing startDate, endDate, and id of undefined.  Is anyone else facing this issue of updating or accessing existing events?  Any help is much appreciated!  

`function deleteEvent(event) {
    var dataSource = $('#calendar').data('calendar').getDataSource();

    for(var i in dataSource) {
        if(dataSource[i].id == event.id) {
            dataSource.splice(i, 1);
            break;
        }
    }
    
    $('#calendar').data('calendar').setDataSource(dataSource);
}`

**Comment by mkyriacou11** [comment]
Hello @echeng924 , 
I know its been a while but do you remember how did you resolve this issue?
