### ISSUE TITLE
event-specific-colors

### ISSUE THREAD

**Issue by jtheim** [Paul-DS/bootstrap-year-calendar#158]
Hi all!
Is it possible to set an individual color for each event? Events are called by database and i plan to set 3 different Colors for "event-types".
Thanks in advance!

**Comment by William-H-M** [comment]
Hi, yes you can on the datasource set `color: #FFFF` (white if not wrong), and that way the color it'll be set, so for the type of event of your database you set it on your code with a switch and that should be it

Note: the colors should be better if you set it with [Hex colors](http://www.color-hex.com/)

**Comment by jtheim** [comment]
Thanks a lot...works fine! Just deleted Color definitions and build a date-array from database including hex Color number.
Best

**Comment by William-H-M** [comment]
Great! as this been solved can we please close this issue? thanks!

**Comment by jtheim** [comment]
Yes, thanks Again!
Best
Johannes

Johannes Theimer - +49 171 5634700 - mobil@JohannesTheimer.de

**Comment by GitKat** [comment]
asdasd
