### ISSUE TITLE
Disabled Week-end ?

### ISSUE THREAD

**Issue by sebastienguay** [Paul-DS/bootstrap-year-calendar#16]
Is it possible to add a parameters that disabled all saturday and sunday of the years?
I find it too : 
line 261
if(j==6 || j==5){
cell.addClass('disabled');
}

In more, if I disabled week-end and I have an event including week end, don't color day like this : 
![image](https://cloud.githubusercontent.com/assets/5238967/14556677/a66e4436-02f9-11e6-9a80-680d8cad16b0.png)

I find with css : 
.disabled{
	box-shadow: none !important;
}

Great Job, I love it !

**Comment by Paul-DS** [comment]
Now, you just have to use the option `disabledWeekDays` like this :

    $('#calendar').calendar({
        disabledWeekDays: [5, 6]
    })

I'll see for implementing an easy option to avoid displaying data source on disabled days (and maybe enable it by default).

**Comment by Paul-DS** [comment]
I added the option. So now you don't need to do anything in CSS, the option is used to enable the data source rendering on disabled days, but this one is disabled by default.

**Comment by sebastienguay** [comment]
It's a very good job! Thanks a lot
But for me it's   disabledWeekDays: [6, 0],
Because weekStart: 1, I think.

**Comment by Paul-DS** [comment]
No, it still [5, 6]. It doesn't depends of the week start.

**Comment by anasmd4** [comment]
how take dates of week days

**Comment by William-H-M** [comment]
@anasmd4 exactly what do you mean?

**Comment by anasmd4** [comment]
i want to take the friday and saturday  dates which i had set as week end..i had used disable week end method to disable it,disabledWeekDays : [ 5, 6 ] function,bt i need the dates which present in 5,6

**Comment by William-H-M** [comment]
Hi Now I get it the plugin doesn't have an option for set all those days of all months but you can do it with a function that disable those day for the 12 month with the [disabledDays ](http://www.bootstrap-year-calendar.com/#Examples/Disable%20days)option
So set a for each day disable it

**Comment by anasmd4** [comment]
hi,
 i wish to get the date of a column which is not set to  disabledWeekDays option. is there any function for that?

**Comment by ikerib** [comment]
Hi,
I also want to disable all week-ends from a given year and I see really interesting the `disabledWeekDays: [6, 0],` option. Nowadays I see that there is no such option and we can use `disabledDays` instead.
This `disabledDays` need a date... so now, the way to go is to obtain an array with all the week-end of a year and set it to `disabledDays` ??
