### ISSUE TITLE
Only displaying one column

### ISSUE THREAD

**Issue by pBauma** [Paul-DS/bootstrap-year-calendar#171]
After testing with different Bootstrap and Calender versions I still can't get the calender to display more than one column.

Tested versions:
Bootstrap version: v4-beta, v3.3.7
jQuery version: v3.2.1
Calender versions: v1.1.0, v1.0.1

HTML code
`<div id="calendar" class="calendar"></div>`

js code
`$(function() {
    $('#calendar').calendar();
});`

![auswahl_020](https://user-images.githubusercontent.com/10058829/30829842-46ed0eea-a242-11e7-81c1-b0e6124e5ff9.png)

Any ideas on how to solve this?

**Comment by pBauma** [comment]
Fixed by downgrading to bootstrap v3

**Comment by fergalddaly** [comment]
This does mean that this is not available for bootstrap v4 ?

**Comment by William-H-M** [comment]
@fergalddaly Hi, yes this library is not available for BS4

**Comment by fergalddaly** [comment]
@William-H-M - Any chance of making it available for BS4 ?  and angular 2 / 4 .  Think it would be widely used if available for both.
