### ISSUE TITLE
events url

### ISSUE THREAD

**Issue by cressije** [Paul-DS/bootstrap-year-calendar#183]
Hello Paul,

Je cherche comment ouvrir une url avec clickDay, en sachant que l'url se trouve dans chaques EVENT (url: 'http://www.google.fr')
Je n'y connais presque rien en java, donc n'hésite pas à être très "basique" !!

Merci pour le travail, et merci d'avance de ton aide
JL

**Comment by Ammar-K** [comment]
if all the URLs point to 'http://www.google.fr' then you can do something like:

$(function() {
    var currentYear = new Date().getFullYear();
    $('#calendar').calendar({
       clickDay: function(e) {
       if(e.events.length > 0) {
               window.open('http://www.google.fr', '_blank');
            }

I'm struggling myself to open unique URL for each event :(

**Comment by cressije** [comment]
Thanks but I search to open unique URL for each event

**Comment by Eloytxo** [comment]
You need to do:

**1. Fill Datasource with your days:**
   Add a property for your custom day event, like :
```
      var day={
             id: xxxxxxx,
             name: yyyyyyyyy,
             ...
             url: 'your custom url here',
             ....
     }
```
  Push day into dataSource array.
**2. Access the url property on render**
```
    $j('#calendar').calendar({
       .....
      dataSource:dataSource,
      clickDay: function(e){
			window.open(e.events[0].url, '_blank');
		},
 });
```

**Comment by Ammar-K** [comment]
Many Thanks @Eloytxo This worked flawlessly.

**Comment by cressije** [comment]
Better late than never : thanks, works fine !
