### ISSUE TITLE
zoom a month

### ISSUE THREAD

**Issue by sebastienguay** [Paul-DS/bootstrap-year-calendar#19]
Is there a way to see only one month in big size like a zoom ?

**Comment by krizajb** [comment]
I would just hide all uninterested months of the year and css the month to your needs.

  var showMonth = new Date().getMonth()+1; // Show only current month

  $('.calendar .month-container').each(function(idx, el){
    if (idx != showMonth ) {
      $(this).css("display","none");
    }
  })

**Comment by sebastienguay** [comment]
Good job! but the size of <td> is the same. So small, not big like a zoom

**Comment by krizajb** [comment]
Well yeah, that's where the css comes in handy, after all only you know how it should/must look like :)

**Comment by anup756** [comment]
`var showMonth = new Date().getMonth()+1; // Show only current month

 $('.calendar .month-container').each(function(idx, el){
    if (idx != showMonth ) {
      $(this).css("display", "none");
    }
 })` 
where does this code go?

**Comment by anup756** [comment]
![captureaa](https://cloud.githubusercontent.com/assets/7366031/15407469/94c5de8c-1dd0-11e6-9c00-7fe40976d560.PNG) ![capturaae](https://cloud.githubusercontent.com/assets/7366031/15407531/f90aab3e-1dd0-11e6-8955-529a2ffb73dc.PNG)![capturey](https://cloud.githubusercontent.com/assets/7366031/15407549/13c13dc6-1dd1-11e6-84a8-11ec15bb8fd4.PNG)

It would be awesome if we could do something like this... I like the event adding part but changes in the calendar would be awesome..

**Comment by krizajb** [comment]
Just to help fellow mates which might be dealing with same issues in the future. This code is pasted after calendar initialization. The code simply hides all months but the selected one8(s). In this case you might be right, since indexing from each loop and getMonth() is both zero based :)

**Comment by Paul-DS** [comment]
@anup756 : The functionality that you are looking for is not the goal of this calendar. The principal goal of this widget is to display a full year view. There is other calendars that propose this type of functionality (i.e. [bootstrap calendar](https://github.com/Serhioromano/bootstrap-calendar))

**Comment by anup756** [comment]
Oh ok cool

**Comment by jcorreia** [comment]
Hi,
nice job with this calendar, but like anup756 says, it would be awesome if we add the option to see only a particular month, more or less like the bootstrap calendar you posted.

Thanks !

**Comment by emreozturk163** [comment]
### ****

> [``](

- [ ] 1. url

)

**Comment by Paul-DS** [comment]
I know this thread is pretty old, but I'm working on this feature in the new version of the library: [js-year-calendar](https://github.com/year-calendar/js-year-calendar)
You can follow the development (and test the functionality) in the PR year-calendar/js-year-calendar#32

**Comment by Paul-DS** [comment]
The feature is available in js-year-calendar@v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
