### ISSUE TITLE
Show the months only vertically

### ISSUE THREAD

**Issue by oscaralmarr** [Paul-DS/bootstrap-year-calendar#196]
![verticaly](https://user-images.githubusercontent.com/6510929/38125562-a480da8e-33ea-11e8-95cd-1d847a4f2694.jpg)

Why I only get the months shown vertically and not as in the examples?
Even with the simplest case. My code is:

Html:
`<div id="calendar"></div>`

And in the javascript call:
`$('#calendar').calendar();`

**Comment by William-H-M** [comment]
Could it be that your div's have a css class that makes their width adjusted?

**Comment by oscaralmarr** [comment]
It was a problem with Bootstrap 4 Integration. I have taken the [neivars fork](https://github.com/neivars/bootstrap-year-calendar) and now is ok!
Thanks!

**Comment by semirci** [comment]
How can I solve the problem with django bootstrap4
