### ISSUE TITLE
Pré-requis

### ISSUE THREAD

**Issue by elecoest** [Paul-DS/bootstrap-year-calendar#2]
Bonjour Paul,

Quels sont les pré-requis pour utiliser ton plugin très prometteur ?
version de bootstrap mini ? 
composants bootstrap (popover, ...) ?

Peux-tu fournir une page avec le code de base pour la page exemple complet ?

Merci beaucoup.

Manu

**Comment by Paul-DS** [comment]
Après quelques tests, tout à l'air de fonctionner jusqu'à la version (minimum) 3.0.0 de bootstrap, et 1.8.0 de jQuery.

Le plugin ne nécessite aucun composant bootstrap spécifique (les fichiers bootstrap/jquery de base suffisent).

Cependant, la mise en place de l'[exemple complet](http://www.bootstrap-year-calendar.com/#Examples/Full%20example) nécessite les composants suivants : 
- [Bootstrap popover](http://getbootstrap.com/javascript/#popovers) (fournit par bootstrap)
- [Bootstrap datepicker](https://github.com/eternicode/bootstrap-datepicker)

Le code de chaque exemple est présent en dessous de l'exemple. J'ajouterai des fiddle pour permettre la customisation des examples.

J'ajouterai sur le site officiel ainsi que sur la page readme de GitHub toutes les informations que je t'ai indiqué.

N'hésite pas si je n'ai pas été clair ou tu as d'autres questions

Paul
