### ISSUE TITLE
Popover interaction not supported

### ISSUE THREAD

**Issue by krizajb** [Paul-DS/bootstrap-year-calendar#20]
Not sure if anyone else needs this but popover implementation doesn't support user interaction. I somehow managed to make a workaround by additionally checking mouseenter/leave event on the popover arrow and bubble and assigned id to every day to properly show/hide the right popover on day hover.

Maybe it comes in handy to someone or you might consider adding additional functionality to your calendar :) Enjoy.

PS: My apologies for any indent inconvenience, no so much fun editing code from here :)

	  // Popup animation control
	  var inBubble = false;
	  var inArrow = false;
	  var inDay = false;

	  // Assign to every day id for animation control
	  var dayId = 0;
	  var shownId = 0;

	  $('.calendar').calendar({
	  style: 'custom',
	  customDataSourceRenderer: function(elt, currentDate, events) {
	    elt.parent().attr('id', dayId++);
	    /* Set other stuff, like background color etc for each day ...*/
	  },

	  mouseOnDay: function(e) {
	    if(e.events.length > 0) {
	      inDay = true;
			
	      var content = '';
	      for(var i in e.events) {
	        content += '<div class="event-tooltip-content">'
	          + 'popover tooltip content ...'
	          + '</div>';
	      }
			
	      $(e.element).popover({ 
	        trigger: 'manual',
	        container: 'body',
	        placement: 'bottom',
	        html:true,
	        content: content
	     });
	    //console.log("Day entered");
			
	     if ($('div.popover:visible').length) {
	       if (shownId != $(e.element).attr('id')) {
	  	     //console.log("Hiding old one, poping new one");
	  	     $('div.popover').hide();
	  	     $(e.element).popover('show');
	  	   }
	      } else {
	        //console.log("Poping new one");
	        $(e.element).popover('show');
	      }
			
	      shownId = $(e.element).attr('id');
	    }
	  },
		
	  mouseOutDay: function(e) {
	    if(e.events.length > 0) {
	      inDay = false;
			
	      setTimeout(function() {
	          if (!inBubble && !inArrow && !inDay) {
	  	        $(e.element).popover('hide');
	          }
	        }, 350);
			
			
	      $(".arrow").mouseenter(function(){
	      //console.log("arrow mouse entered");
	      inArrow = true;
			  
	      }).mouseleave(function(){
	     //console.log("arrow mouse left");
			  
	      setTimeout(function() {
	  	if (!inBubble && !inDay) {
	  	    $(e.element).popover('hide');
	  	}
	      }, 10);
			  
	      inArrow = false; 
	    });
			
	    $(".popover").mouseenter(function(){
	      //console.log("bubble mouse entered");
	      inBubble = true;
			  
	    }).mouseleave(function(){
	      //console.log("bubble mouse left");
			  
	           setTimeout(function() {
	              if (!inArrow && !inDay) {
	            $(e.element).popover('hide');
	        }
	      }, 10);
			  		  
	      inBubble = false;
	    });	
	    }
	  }
	});

**Comment by Paul-DS** [comment]
The popover is not currently managed in the calendar, because otherwise I have to add the popover component as a requirement of the calendar, and I want to keep it as light as possible.
So the popover management is not planned for the moment, I will see maybe later, if several people ask me the same thing.

Concerning your problem, I found a solution without using ids :)

You can the example [here](http://www.bootstrap-year-calendar.com/test_krizajb/)
Maybe make some advanced tests, to be sure that there is no issues compared to your solution.

This is the code:

```
function hidePopover(elt) {
	// Hiding the popover only if the mouse is not on the day AND not on the popover.
	if(!elt.data('mouse-on-day') && !elt.data('mouse-on-popover')) {
		elt.popover('hide');
	}
}
```

```
mouseOnDay: function(e) {
	if(e.events.length > 0) {
		$(e.element).data('mouse-on-day', true);
	
		var content = '';
		
		for(var i in e.events) {
			content += '<div class="event-tooltip-content">'
							+ '<div class="event-name" style="color:' + e.events[i].color + '">' + e.events[i].name + '</div>'
							+ '<div class="event-location">' + e.events[i].location + '</div>'
						+ '</div>';
		}
	
		// Initialize the popover
		var popover = $(e.element).popover({ 
			trigger: 'manual',
			container: 'body',
			html:true,
			content: content,
			placement: 'bottom'
		});
		
		// Get the popover DOM element
		var popover =  $(e.element).data('bs.popover').tip();
		
		var alreadyVisible = false;
		
		// Hide all the old popover visible (only for the case of switching of two adjacent popover).
		$('div.popover:visible').each(function() {
			if($(this).get(0) == popover.get(0)) {
				alreadyVisible = true;
			}
			else {
				// If the popover is not the current one, hide it.
				$(this).hide();
			}
		});
		
		if(!alreadyVisible) {
			$(popover).mouseenter(function () {
				$(e.element).data('mouse-on-popover', true);
			})
			
			$(popover).mouseleave(function () {
				$(e.element).data('mouse-on-popover', false);
				
				setTimeout(hidePopover, 50, $(e.element));
			})
		
			$(e.element).popover('show');
		}
	}
},
mouseOutDay: function(e) {
	if(e.events.length > 0) {
		$(e.element).data('mouse-on-day', false);
			
		setTimeout(hidePopover, 50, $(e.element));
	}
},

```

Tell me if you find something or if you have some better ideas.

**Comment by krizajb** [comment]
Cool, thanks! Hope someone else finds it useful, I will update my page later tomorrow and do some testing but so far looks good and the code is a lot cleaner.

**Comment by anup756** [comment]
**Problem:** Popover for last day not showing up with new commit in master(`May 19,2016`).

**Comment by maliayan** [comment]
For Bootstrap 4, the code @Paul-DS wrote works, but with a small change:

Use this:
`var popover =  $(e.element).data('bs.popover').getTipElement();`

Instead of this:
`var popover =  $(e.element).data('bs.popover').tip();`


I spent lots of time to solve the problem on Bootstrap 4. So, if there is anyone who suffers from the same problem, they can use this info.

**Comment by mkyriacou11** [comment]
@maliayan Thank you very much, you have solved my issue.

But i still have a problem with the popover, as soon as i hover it, it disappears. 
Do you know how to fix it?

**Comment by maliayan** [comment]
@mkyriacou11 You're welcome! Nice to hear this.

I used it a long time ago, so I cannot remember everything. Could you please share your code if it is possible? If you solved the problem, maybe you can share your solution :)

**Comment by MikeFrom** [comment]
Hi @Paul-DS, popover hides at once on my iPad with Safari. Any ideas? Thanks
