### ISSUE TITLE
 November 30 does not appear

### ISSUE THREAD

**Issue by Giovani-Silva** [Paul-DS/bootstrap-year-calendar#210]
![image](https://user-images.githubusercontent.com/6223139/40367997-1188a7ac-5db1-11e8-8fec-372185d5ed43.png)

**Comment by Giovani-Silva** [comment]
Sorry,
It was some bug in the browser

**Comment by hallss93** [comment]
@Giovani-Silva  how done you solve this prroblem?

**Comment by hallss93** [comment]
#109  solve @Giovani-Silva @djulianm have done one solution

**Comment by Giovani-Silva** [comment]
Great,  solution works .

**Thank´s** **@djulianm** for solution

**Thank´s** **@hallss93**
