### ISSUE TITLE
Same Background Color

### ISSUE THREAD

**Issue by Benjaminscherf** [Paul-DS/bootstrap-year-calendar#213]
I use the calendar with the half day option. Is there an opportunity to reduce the background color to one single color?

**Comment by garth1138** [comment]
In your dataSource, you can specify the color for each entry by adding "color:'[colorHexCode]'" as part of your data. If color is defined for an entry it will be applied. With no color defined, then it will cycle through the five predefined colors. I use it to show different types of entries based on type in data.
Example: dataSource: [{id:29844, type:'PTO', hours:8, color:'#668cff', startDate: new Date(2015,3,8), endDate: new Date(2015,3,8)}]

**Comment by Benjaminscherf** [comment]
Thank you
