### ISSUE TITLE
Custom Day Number (Text) using customDataSourceRenderer

### ISSUE THREAD

**Issue by juppinger0** [Paul-DS/bootstrap-year-calendar#219]
Hi all,

I just want to set a different style to some "special" days. So I'm playing with customDataSourceRenderer.

my problem: 
I want to set a different TEXT for a day. 
instead of the day number (eg. "31" I want to use another letter eg. "_(!)").

I played around with some code snippets but I always get the result that the popup will never appear if I change the text.

`(...)
        style: 'custom',		
        customDataSourceRenderer: function(element, date, events) { 
(...)`

`(...)
        dataSource: [
            {
                id: 0,
                name: 'Google I/O',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 4, 28),
                endDate: new Date(currentYear, 4, 29),
                typ: 'wichtig'
            },
(...)`

`(...)
$(function() {
    var currentYear = new Date().getFullYear();

    $('#calendar').calendar({ 
        style: 'custom',		
        customDataSourceRenderer: function(element, date, events) {    
            for (var i=0; i<events.length; i++) {                        
                if(events[i].typ == 'wichtig') {                    
                   $(element).css('color', 'red');
                   $(element).text($(element).text() + "_(!)");
                }                
                if(events[i].typ == 'unwichtig') {
                   $(element).css('background-color', 'green');
                }                
            }
        },
(...)`

This is my COMPLETE sample code (you should copy paste 1 by 1 for local testing):

`

  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <link rel="stylesheet" href="https://www.bootstrap-year-calendar.com/download/v1.1.0/bootstrap-year-calendar.min.css">
  
  <script src="https://www.bootstrap-year-calendar.com/download/v1.1.0/bootstrap-year-calendar.min.js"></script>
  
  

</head>
<body>

<div id="calendar" class="calendar"></div>

<script>
function editEvent(event) {
    $('#event-modal input[name="event-index"]').val(event ? event.id : '');
    $('#event-modal input[name="event-name"]').val(event ? event.name : '');
    $('#event-modal input[name="event-location"]').val(event ? event.location : '');
    $('#event-modal input[name="event-start-date"]').datepicker('update', event ? event.startDate : '');
    $('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.endDate : '');
    $('#event-modal').modal();
}

function deleteEvent(event) {
    var dataSource = $('#calendar').data('calendar').getDataSource();

    for(var i in dataSource) {
        if(dataSource[i].id == event.id) {
            dataSource.splice(i, 1);
            break;
        }
    }
    
    $('#calendar').data('calendar').setDataSource(dataSource);
}

function saveEvent() {
    var event = {
        id: $('#event-modal input[name="event-index"]').val(),
        name: $('#event-modal input[name="event-name"]').val(),
        location: $('#event-modal input[name="event-location"]').val(),
        startDate: $('#event-modal input[name="event-start-date"]').datepicker('getDate'),
        endDate: $('#event-modal input[name="event-end-date"]').datepicker('getDate')
    }
    
    var dataSource = $('#calendar').data('calendar').getDataSource();

    if(event.id) {
        for(var i in dataSource) {
            if(dataSource[i].id == event.id) {
                dataSource[i].name = event.name;
                dataSource[i].location = event.location;
                dataSource[i].startDate = event.startDate;
                dataSource[i].endDate = event.endDate;
            }
        }
    }
    else
    {
        var newId = 0;
        for(var i in dataSource) {
            if(dataSource[i].id > newId) {
                newId = dataSource[i].id;
            }
        }
        
        newId++;
        event.id = newId;
    
        dataSource.push(event);
    }
    
    $('#calendar').data('calendar').setDataSource(dataSource);
    $('#event-modal').modal('hide');
}

$(function() {
    var currentYear = new Date().getFullYear();

    $('#calendar').calendar({ 
        style: 'custom',		
        customDataSourceRenderer: function(element, date, events) {    
            for (var i=0; i<events.length; i++) {                        
                if(events[i].typ == 'wichtig') {                    
                   $(element).css('color', 'red');
                   $(element).text($(element).text() + "_(!)");
                }                
                if(events[i].typ == 'unwichtig') {
                   $(element).css('background-color', 'green');
                }                
            }
        },
        enableContextMenu: true,
        enableRangeSelection: true,
        contextMenuItems:[
            {
                text: 'Update',
                click: editEvent
            },
            {
                text: 'Delete',
                click: deleteEvent
            }
        ],
        selectRange: function(e) {
            editEvent({ startDate: e.startDate, endDate: e.endDate });
        },
        mouseOnDay: function(e) {
            if(e.events.length > 0) {
                var content = '';
                
                for(var i in e.events) {
                    content += '<div class="event-tooltip-content">'
                                    + '<div class="event-name" style="color:' + e.events[i].color + '">' + e.events[i].name + '</div>'
                                    + '<div class="event-location">' + e.events[i].location + '</div>'
                                + '</div>';
                }
            
                $(e.element).popover({ 
                    trigger: 'manual',
                    container: 'body',
                    html:true,
                    content: content
                });
                
                $(e.element).popover('show');
            }
        },
        mouseOutDay: function(e) {
            if(e.events.length > 0) {
                $(e.element).popover('hide');
            }
        },
        dayContextMenu: function(e) {
            $(e.element).popover('hide');
        },
        dataSource: [
            {
                id: 0,
                name: 'Google I/O',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 4, 28),
                endDate: new Date(currentYear, 4, 29),
                typ: 'wichtig'
            },
            {
                id: 1,
                name: 'Microsoft Convergence',
                location: 'New Orleans, LA',
                startDate: new Date(currentYear, 2, 16),
                endDate: new Date(currentYear, 2, 19),
                typ: 'unwichtig'
            },
            {
                id: 2,
                name: 'Microsoft Build Developer Conference',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 3, 29),
                endDate: new Date(currentYear, 4, 1),
                typ: 'wichtig'
            }
        ]
    });
    
    $('#save-event').click(function() {
        saveEvent();
    });
});
</script>

`

Thanks in advance!
jupi

**Comment by Paul-DS** [comment]
Can you provide a clear example please.

You can create a fiddle based on https://jsfiddle.net/3vb4dmpj/

**Comment by Rbalyk** [comment]
@Paul-DS I am working with your js-year-calendar its Amazing but I have little bit questions that I cant find answer. Is it possible to connect with you on 10min in skype or something else?
