### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by Nikdro** [Paul-DS/bootstrap-year-calendar#22]
Is it possible to change the colours without manipulating bootstrap-year-calendar.js?

It would be very helpful :+1: :-)

**Comment by Paul-DS** [comment]
Yes, you just have to set the `color` property of each data source item, like the following example:

	$('#calendar').calendar({ 
		dataSource: [
			{
				startDate: new Date(2016, 1, 4),
				endDate: new Date(2016, 1, 15),
				color: 'yellow'
			},
			{
				startDate: new Date(2016, 2, 7),
				endDate: new Date(2016, 2, 11),
				color: 'pink'
			},
			{
				startDate: new Date(2016, 3, 5),
				endDate: new Date(2016, 5, 15),
				color: '#48A38C'
			}
		]
	});

You can find the example here : http://www.bootstrap-year-calendar.com/test_nikdro/

**Comment by Nikdro** [comment]
Thank you for the fast answer!

**Comment by josegeraldocosta** [comment]
Taking advantage about issue,
is it possible change background without manipulating bootstrap-year-calendar.js? just like color?
