### ISSUE TITLE
Provide a bootstrap 4.x compatible version of the library

### ISSUE THREAD

**Issue by anlambert** [Paul-DS/bootstrap-year-calendar#225]
Hi,

As bootstrap 3.x is no longer maintained, it would be nice to have a bootstrap 4.x compatible version of that great library available on npm.

In PR #170,  @neivars did that porting job and I can confirm it works as I use it in production
on the website I am working on (see https://archive.softwareheritage.org/browse/origin/https://github.com/torvalds/linux/visits/ as an example). Currently I am forced to use a patched version of it due to a needed modification in the package.json (see https://github.com/anlambert/bootstrap-year-calendar/commit/a51523192c72e037545930d9d0e4306d54c7ce53). 

I would rather use an official version of that port so it would be nice if PR #170 could be merged (maybe in a separate branch) and a bootstrap 4 compatible version of the package uploaded on npm (it could be name `bootstrap-year-calendar-bs4` for instance).

Cheers!

**Comment by Paul-DS** [comment]
Let's continue the discussion in #170
