### ISSUE TITLE
contextMenuItems?

### ISSUE THREAD

**Issue by JolyneAnasui** [Paul-DS/bootstrap-year-calendar#238]
i wonder what's the function of code below, it's an option in calendar.
`contextMenuItems:[
            {
                text: 'Update',
                click: editEvent
            },
            {
                text: 'Delete',
                click: deleteEvent
            }
        ],`

**Comment by thaqiftaher** [comment]
Hi there,

This function will be fired when a day is right clicked. If you refer to the full example [here](http://www.bootstrap-year-calendar.com/#Examples/Full%20example), you can edit the information for the specific date.

**Comment by Taeboush** [comment]
much thanks.@thaqiftaher
omg, my poor english, i didn't see the word 'right' and i've try everything to find the function of it but fail.
