### ISSUE TITLE
Add method for reset data source

### ISSUE THREAD

**Issue by atukilham** [Paul-DS/bootstrap-year-calendar#24]
hi, thanks for the plugin.
it's very useful for me.
i have one suggestion, i think we need add one method for reset data source.
but ignore it if not important..
thanks :)

**Comment by Paul-DS** [comment]
Hi !

Thank you for your remark. It's interesting, but I think that the current way to reset a data source is quite simple, and doesn't need to be simplified:
`$('#calendar').data('calendar').setDataSource([]);`

For example, implementing a method `resetDataSource` doesn't save any character (2 characters more in the method name, 2 less for the parameters).

**Comment by atukilham** [comment]
oh nice..i see that.
thanks :)
