### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by Jogai** [Paul-DS/bootstrap-year-calendar#252]
There are a some open pull request and some forks getting ahead (like the ones from @technobulka and @webworksnbg just to name a few) and even a different release on npm (from @anlambert). Is this project still meant to be maintained?

**Comment by Paul-DS** [comment]
The project has been rewrite to remove the bootstrap and jquery dependencies.
You can find it here: https://github.com/year-calendar/js-year-calendar
I didn't depreciate the current repository since I don't have enough feedback on the new version of the library, but I'll do it in the next weeks/months.

**Comment by Jogai** [comment]
Good to know. I'll look into migrating my current setup and see how well everything carries over.

**Comment by anlambert** [comment]
@Paul-DS, I will also migrate my project to [js-year-calendar](https://github.com/year-calendar/js-year-calendar) when I found some time to do it. I will deprecate [bootstrap-year-calendar-bs4  ](https://www.npmjs.com/package/bootstrap-year-calendar-bs4) once it is done.

**Comment by anlambert** [comment]
@Paul-DS , just to let you know I have finally deprecated the `bootstrap-year-calendar-bs4` package on [npm](https://www.npmjs.com/package/bootstrap-year-calendar-bs4) and [github](https://github.com/anlambert/bootstrap-year-calendar-bs4).

Honestly, you should release a `1.0.0` version of [`js-year-calendar`](https://github.com/year-calendar/js-year-calendar) as I use the current alpha version in production and apart a couple of CSS tweaks for the [port from `bootstrap-year-calendar`](https://forge.softwareheritage.org/rDWAPPSd00fea338279fc8c262b21a7295bd4712c0769c2) it works like a charm as before, see [this](https://archive.softwareheritage.org/browse/origin/https://www.npmjs.com/package/js-year-calendar/visits/) for instance ;-).

**Comment by ikerib** [comment]
Hello!
5 years ago I developed a calendar management application for the company and now I have to update it.
I used this library (What a great job!) and now that I'm going to redo the application I see that there are no new commits for more than a year and I wonder the same .... if the project is still in maintenance or if there is any alternative.

**Comment by Paul-DS** [comment]
Yes, this repository is deprecated. You should consider using https://year-calendar.github.io/
