### ISSUE TITLE
Issue With Bootstrap 4 : Months Calendar Box is showing vertical

### ISSUE THREAD

**Issue by ImAbhishekTomar** [Paul-DS/bootstrap-year-calendar#256]
My calendar is not showing as per example horizontal monthly view... all months calendar box showing vertical... please help snapshot below.

**Code**
```
<div id="calendar" data-provide="calendar"></div>
 $(function () {
            var currentYear = new Date().getFullYear();
            $('#calendar').calendar({
                allowOverlap: true,
                displayWeekNumber: true,
                enableContextMenu: true,
                enableRangeSelection: true,
                minDate: new Date(2019, 01, 10),
                maxDate: new Date(2019, 12, 31),
                roundRangeLimits: true,
            })
    });
```

![image](https://user-images.githubusercontent.com/6933841/63889813-58d4ab80-ca14-11e9-9a45-add4f89b1e7f.png)

**Comment by William-H-M** [comment]
Hi, currently this plugin is not adapted for BS4, if not wrong there´re some repos that have it, reference to #170
