### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by JeongYoungHo** [Paul-DS/bootstrap-year-calendar#26]
hi 
how to open context menu?
right click?

**Comment by Paul-DS** [comment]
To enable the context menu, you need to:
- Set the `enableContextMenu` option to true
- Set the different menu items (and their behavior) that you want, using the `contextMenuItems` options.

You can find an example on this [page](http://www.bootstrap-year-calendar.com/#Examples/Full example)

Then, you can open the context menu by right clicking on a date which contain an event.

**Comment by kannratha** [comment]
Hi I already have enable enableContextMenu but it still not work.
Can you help?

**Comment by kannratha** [comment]
enableRangeSelection: true,
        contextMenuItems:[
            {
                text: 'Update',
                click: editEvent
            },
            {
                text: 'Delete',
                click: deleteEvent
            }
        ],  
dayContextMenu: function(e) {
            console.log(e);
            $(e.element).popover('hide');
        }

**Comment by JeongYoungHo** [comment]
In example code it does not open context menu.
but it is set `enableContextMenu` true.
when i received answer from @Paul-DS it did not work.

**Comment by corwin32** [comment]
Hi,
using example, all working well but context menu working abit weird, when i right click menu shows but on mouse release disapear, so i have to hold right mouse button and then left click to selected option.

Is this wanted design or im missing something ?

thanx

**Comment by Linbubin** [comment]
@corwin32  you can look #40  , it works good.
