### ISSUE TITLE
minDate/maxDate bug

### ISSUE THREAD

**Issue by apmyp1990** [Paul-DS/bootstrap-year-calendar#28]
Hi,
when i set the minDate and the maxDate for only showing a previous year, it still shows the actual year, but disabled (see picture 1). In the header it shows the actual year, the year I want and all years in between the actual and my year. When I click on my year, all other years disappear und everything is fine (see picture 2).

Is there any solution to solve this bug?

Thanks

Pic. 1:
![2016-06-27 08_29_35-24 local - iron](https://cloud.githubusercontent.com/assets/20161590/16370643/ad33faf0-3c41-11e6-8632-aa47b09b206a.jpg)

Pic. 2:
![2016-06-27 08_30_34-24 local - iron](https://cloud.githubusercontent.com/assets/20161590/16370648/b533714a-3c41-11e6-8e9b-b4d3afd69ee1.jpg)

**Comment by Paul-DS** [comment]
For the moment you can just set manually the year (using the `setYear` method). I will think about implementing an automatic selection of the year when changing the minDate/maxDate.

**Comment by apmyp1990** [comment]
HI,
thanks for your quick response. For the moment I solved it with js, just clicking on the right year, but I will change it to setYear.

Regards,
Artur

>Понедельник, 27 июня 2016, 23:45 +02:00 от Paul-DS <notifications@github.com>:
>
>For the moment you can just set manually the year (using the setYear method). I will think about implementing an automatic selection of the year when changing the minDate/maxDate.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Artur Schwenke
