### ISSUE TITLE
Un mois de décalage 

### ISSUE THREAD

**Issue by dabcorp** [Paul-DS/bootstrap-year-calendar#30]
Bonjour,

J'ai un petit problème ou alors je ne comprend pas bien ...
Voici un exemple de mon dataSource (champ mysql de type date ):
```
dataSource: [ {startDate: new Date(2016,07,02
),endDate: new Date(2016,07,02)},{startDate: new Date(2016,07,28),endDate: new Date(2016,07,28)} ]
```
lors du l’affichage , j’ai un mois de décalage : ( 2016-07-28 ==> Juillet  / Affichage ==> Aout)
![capture](https://cloud.githubusercontent.com/assets/2905132/16540304/6a9e3afc-4060-11e6-91b4-e74078317781.PNG)

Merci par avance de votre aide :)

Cordialement ,

**Comment by Paul-DS** [comment]
Bonjour,

Ce n'est pas un bug. L'objet "Date" JavaScript gère les mois de 0 à 11, contrairement au reste (jours, années, etc.). Je te redirige vers l'issue #11 où tu pourras trouver plus d'informations à ce sujet.

N'hésite pas si tu as d'autres questions !

**Comment by dabcorp** [comment]
Arf, je m'en  doutais. Je vais essayer de modifier ma requête SQL.

**Comment by Paul-DS** [comment]
Comment passes-tu tes données à ton javascript ? Je te dirait plutôt de modifier le mapping "back-end code" <-> javascript, car ce problème concerne le javascript, pas le SQL. Si un jour tu as besoin de pré-traiter tes données avant de les utiliser en javascript, il faut que ton back-end aient tes dates au format standard, et non javascript. Enfin cela ne concerne plus le calendar :)

**Comment by dabcorp** [comment]
Je récupère les données via une requête SQL sur un champs date de ma table réservation. Je passe ensuite cela via un array et l'inject  dans mon template via Fat-free.

**Comment by Paul-DS** [comment]
Je ne connais pas ce framework, mais de ce que je vois de leur format de templates, tu devrait pouvoir modifier ton numéro de mois dedans :
`new Date({{ @year }}, {{ @month -1 }}, {{ @day }});`

**Comment by dabcorp** [comment]
Exactement :). Merci à toi et allez les bleus.
