### ISSUE TITLE
background color by event properties

### ISSUE THREAD

**Issue by josegeraldocosta** [Paul-DS/bootstrap-year-calendar#31]
is it possible change background without manipulating bootstrap-year-calendar.js? just like color?

**Comment by Paul-DS** [comment]
For the entire calendar ? Or just for some specific days ?

If it's for the entire calendar, you just have to apply some CSS rule on the calendar days.
Otherwise, you can use the `customDataSourceRenderer`.

Don't hesitate if you have some questions.
