### ISSUE TITLE
Initialisation exemple

### ISSUE THREAD

**Issue by Matilas83** [Paul-DS/bootstrap-year-calendar#37]
Hello Paul,

Avant tout, merci beaucoup, ton calendar est exactement ce que je recherche. Malheureusement, je n'arrive même pas à générer un exemple en local. Je fus développeur, j'ai décroché un temps et là je m'y remets pour un projet perso.
J'ai bien télécharger ton package + bootstrap 3.3.7 + jquery 3.1.0

Cependant, quand je veux générer un calendrier grâce au JS "$('.calendar').calendar();", rien ne se produit alors que mes "alert" pop bien. Quand j'utilise les balises "<div data-provide="calendar"></div>" le calendrier se génère correctement.

Je ne saisis pas ce que je fais mal.

Merci pour ton aide

Mathias

**Comment by marouenayadi** [comment]
$('.calendar-demo').calendar();

**Comment by Matilas83** [comment]
Hello, merci pour l'astuce mais même résultat :(
Pas de calendrier généré

Mathias

**Comment by Paul-DS** [comment]
> Quand j'utilise les balises " " le calendrier se génère correctement.

C'est à dire ?

Tu as bien inclus tes fichiers javascript dans ta page html ?

Tu peux comparer avec l'exemple complet que j'avais fait  : [full-example.zip](https://github.com/Paul-DS/bootstrap-year-calendar/files/100029/full-example.zip) (cet exemple utilise une ancienne version du plugin, c'est juste pour t'aider à analyser d'où vient le problème)

**Comment by Matilas83** [comment]
Hello Paul,

Merci pour ton source example. My bad, ça a été une incompréhension de ma part de ton usage
> You can create a calendar using the following javascript code :
> `$('.calendar').calendar()`
> or
> `$('.calendar').calendar(options)`
> or with the data-provide html attribute
> `<div data-provide="calendar"></div>`

Je pensais que l'on pouvait générer le calendrier par l'appel simple de 
1. JS (calendrier simple)
2. ou JS (calendrier avec options)
3. ou Balise HTML

Mais en fait la balise HTML est obligatoire (notamment pour situer le calendrier dans la page, quand j'y réfléchis)

En tout cas merci pour ton aide et merci pour ton super boulot !!

Mathias
