### ISSUE TITLE
+1 Day event 

### ISSUE THREAD

**Issue by marouenayadi** [Paul-DS/bootstrap-year-calendar#38]
@Paul-DS 

```
$.getJSON( "URL" , function(data) {
         var i = 0;
          $.each( data, function( key, value ) {
     var ev = {}
        ev['id'] = i;
        ev['name'] = value.EVT_Title;
        ev['startDate'] =new Date(value.EVT_Date);
        ev['location'] = value.EVT_Title;
        ev['endDate'] = new Date(value.EVT_Date)    ;
        ev['endDate'] = ev['startDate'].addDays(1); 
        eventOfJson.push(ev);

        i = i+1;

```

This is my code to get events from a web service , the statDate and the endDate are equals for example the startDate is ( 04/01/2016 ) but the event appears at the end ( 05/01/2016 ) like the endDate add + 1day 
what should i do please `

**Comment by Paul-DS** [comment]
It seems to be normal, since you set the `endDate` to `startDay.addDays(1)` ?
If you want to display the event only on the day of the `startDate`, you can use the same value for the `startDate` and the `endDate`.
