### ISSUE TITLE
datasource: month-1 for actual month

### ISSUE THREAD

**Issue by dc1wh** [Paul-DS/bootstrap-year-calendar#39]
Hello,

when i add a timeframe to the datasource, i have to put in a different month number, than the month actually has. 

### Example:
Vacation from Oct, 27th till Nov, 10th.
Date: **27.10.2016** till **10.11.2016**

### Datasource entry:

    dataSource: [
        {
            id: 0,
            name: 'Vacation',
            startDate: new Date(2016, **09**, 27),
            endDate: new Date(2016, **10**, 10)
        }
    ]

thats counterintuitive and leads to errors for users with less programming experience.

**Comment by Paul-DS** [comment]
I'm agree with you, but this is not coming from my plugin.

This is the specification of the date object in javascript : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

> **month**
> Integer value representing the month, beginning with 0 for January to 11 for December.
