### ISSUE TITLE
index?

### ISSUE THREAD

**Issue by silguilo** [Paul-DS/bootstrap-year-calendar#4]
You could upload the index.html file?

**Comment by Paul-DS** [comment]
What do you call the index.html file ?
If you need example you can look at the [exemple](http://www.bootstrap-year-calendar.com/#Examples) page of the official website.

To use the plugin you just have to include jQuery, Bootstrap, and the javascript and css file of the plugin. Then you can use the calendar, as describe in examples.

**Comment by silguilo** [comment]
It is that I'm learning and I'm not sure how to implement it. That's why I asked the index, to see how they were getting into on a page. Pleasee...

**Comment by Paul-DS** [comment]
The simple example, with all required files : [simple-example.zip](https://github.com/Paul-DS/bootstrap-year-calendar/files/66027/simple-example.zip)

**Comment by silguilo** [comment]
thank you very very very muuuch
Muchas gracias desde España
:)
