### ISSUE TITLE
Right click is not working on linux and Mac OS 

### ISSUE THREAD

**Issue by birkansava** [Paul-DS/bootstrap-year-calendar#40]
I'm trying to edit my event by right click , It's working on windows perfectly but not working on mac or linux.(I have to hold right click and then left click on edit link.) . how can i solve?

**Comment by nicoalonsop** [comment]
Hi, I have the same problem and in mac with the magic mouse or the trackpad i can´t do left click when holding right click.
I try removing preventDefault and now i have to right click, press ESC and then select the option on context menu 
It is not a solution but the users can use it.

Do you solve it?

**Comment by birkansava** [comment]
no :(

**Comment by sfaraujo** [comment]
I solve it with this:

on line 716 (bootstrap-year-calendar.js ) change

`$(window).one('mouseup', function() {`

to 

`$(window).click(function() {`

**Comment by vnikiet** [comment]
Thanks sfaraujo! u save my day!
