### ISSUE TITLE
Date format in dataSource

### ISSUE THREAD

**Issue by nahouto** [Paul-DS/bootstrap-year-calendar#41]
Bonjour,

Bravo aussi pour ce bel outil !

Je recupere mes donnees d'une database et je ne sais pas formatter la date correctement pour qu'elle soit bien interpretee par le bootstrap-year-calendar.

Meme en mettant exactement au format "Tue Nov 17 2016 00:00:00 GMT+0200 (IST)", c'est interprete comme en String et non comme une date, et ca ne fonctionne pas...

Merci !

**Comment by Paul-DS** [comment]
Actuellement le calendrier ne gère pas les dates passées en "string", c'est pourquoi tes données ne sont pas interprétées.
La solution est donc de transformer tes objets string en date, comme dans l'exemple suivant:

    // data contient les données provenant de ta base de données
    var calendarData = [];
    for(var i = 0; i < data.length; i++) {
        calendarData.push(new {
            startDate: new Date(data[i].startDate),
            endDate: new Date(data[i].endDate),
            color: data[i].color
        });
    }

    calendar.setDataSource(calendarData);

**Comment by nahouto** [comment]
Merci, ca marche !
