### ISSUE TITLE
Calender overlap Two Year

### ISSUE THREAD

**Issue by indrazeal** [Paul-DS/bootstrap-year-calendar#43]
HI. . .
Thanks for awesome plugin.
I have problem to show calender in year  2016-2017 interval Aug 2016 - Aug 2017, Can you tell me how to make it ?

**Comment by indrazeal** [comment]
I found it
just edit function _renderBody
 for(var m = 0; m < 12; m++) { // 12 month
}

edited

for(var m = 0; m < 9; m++) {
}

for(var m = 9; m < 12; m++) {
}

Thanks

**Comment by Paul-DS** [comment]
I know this thread is pretty old, but I'm working on this feature in the new version of the library: [js-year-calendar](https://github.com/year-calendar/js-year-calendar)
You can follow the development (and test the functionality) in the PR year-calendar/js-year-calendar#32

**Comment by Paul-DS** [comment]
The feature is available in js-year-calendar@v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
