### ISSUE TITLE
name property "hardcoded" in context menu

### ISSUE THREAD

**Issue by PrinceOfAbyss** [Paul-DS/bootstrap-year-calendar#45]
I had a look into the .js and found out that startDate and endDate properties are hardcoded, so I didn't those two (in fact I initially touched them, and the plugin stopped working). So, I renamed all needed properties to my needs for easier recognition, and left those two untouched. But then, I realized there is a problem when I right-click on a day to disply the context menu with Edit and Delete options. So I found that the "first-level" menu is hardcoded to events[i].name leaving my context menu empty (only with the right-pointing chevron arrow).

There a couple of workarounds here, like reverting back the rate property's name to name, or hardcoding into my saveEvent method a static property named name, some word obviously, like Actions, that will make sense as the "first-level" option in the context-menu. But to be honest, I'd prefer to totally omit the first level menu, so by right-clicking on a day will bring the two options. Is there a method for re-designing the context menu, or do I have to edit the source .js file?

Take a look at how it's displayed right now, and please advise me what's my best approach on this.

![name](https://cloud.githubusercontent.com/assets/21269021/18025213/033a048a-6c2b-11e6-8413-82b4dded91bc.png)

**Comment by noncototient** [comment]
Look for my reply in here: https://github.com/Paul-DS/bootstrap-year-calendar/issues/46

Look for $.get and data processing bit.

**Comment by PrinceOfAbyss** [comment]
Unfortunately, you didn't understand my question. The reply you quoted doesn't have anything to do with the problem I'm mentioning here. What I need is a way to re-design the context menu so that I get rid of the first-level option (the "name" of the event).

Basically, I realized yesterday that when there are overlapping events for the same period, those events are displayed there with the Edit and Delete options for each of them. But if you remember my case, I'll be using the background property so that only the latest event is visible for each day. So, it'll be inconsistent to list all events for edition/deletion when the user pops the context menu.

Take a look at the images below to better understand what I mean:

![two](https://cloud.githubusercontent.com/assets/21269021/18035727/fcc7eaa6-6d63-11e6-83d5-92e53957356c.png)

Here I have two monthly events, with a price for each event.

![overlap](https://cloud.githubusercontent.com/assets/21269021/18035726/fca63668-6d63-11e6-8105-45b7420b3ea2.png)

Here I put a single two-month event that overlaps the other two. Background color makes sure that only the top event is displayed at any time, but then, when the user right clicks on a day to display the context menu, bam, both events are shown. Isn't this inconsistent? So, I'll have to alter the context menu calculation algorithm. and instead of looping through the events of that day, I'll be only displaying the last one. But there is no method for doing that in my config file. I'll have to hardcode it in the plugin's JS directly. Any ideas?

**Comment by noncototient** [comment]
> What I need is a way to re-design the context menu so that I get rid of the first-level option (the "name" of the event).

I haven't actually used this myself yet, but I assume it displays days using a loop to go through array of options for that day. Would you be able to simply use the last element of that loop to be the option for that day? 

For instance, to display the options for a specific day you would have:
```
for(var i = 0; i < optionsInDay.length; i++){
    console.log(optionsInDay[i]); // <--- that would display the days and their corresponding Edit & Delete
}
```

So you might just use something like this:
` optionsInDay[optionsInDay.length-1]`

This is rough and from the top of my head, but it might work :)

**Comment by PrinceOfAbyss** [comment]
There is no method for editing the context menu. That's the problem!

**Comment by Paul-DS** [comment]
Hi,

Thank you for your remarks.

You can actually customize the context menu by using the `dayContextMenu` event of the calendar (see in the [documentation](http://www.bootstrap-year-calendar.com/#Documentation/Events)).
In your event method, you can create either a full custom menu, or build a menu using the same CSS classes used in the calendar widget : 
- `.calendar-context-menu`
 - `.item`
   - `.submenu`
     - `.item`

etc...

You can take exemple on the `_openContextMenu` method of the calendar, which is used to generate the context menu for a day.

Don't hesitate if you have some trouble during implementation, or some good ideas to simplify the customization.

**Comment by noncototient** [comment]
> There is no method for editing the context menu. That's the problem!

Yeah I should've mentioned before that what I proposed would require going into the source code of the plugin and making modifications. 

But looks like @Paul-DS has provided a better solution :)
