### ISSUE TITLE
Need help binding dataSource - ASP.NET MVC project

### ISSUE THREAD

**Issue by nmathurbkn** [Paul-DS/bootstrap-year-calendar#49]
Hello Paul,

First of all I want to thank you for creating such a useful widget.

I am developing a web project using ASP.NET MVC C#. All working fine but I am facing an issue. It may be because of my mistake but I really need to complete it today. Please help me with this.

My dataSource is binding, I am able to load the details on "mouseOnDay" but the style to set color on dates is not applying. After debug I found out that at the time of "this._initializeDatasourceColors();" the dataSource is on binding in calendar's options. Rest options are passing perfectly (startYear,          allowOverlap, enableRangeSelection etc). 

Here is what I am doing to fetch the data : 

```
 function getMyData() {

            var myData= [];
            $.ajax({
                url: 'Index/holiday',
                success: function (response) {
                    for (var i = 0; i < response.length; i++) {
                        myData.push({
                            id: response[i].id,
                            title: response[i].title,
                            startDate: new Date(response[i].startDate),
                            endDate: new Date(response[i].endDate),
                           color: response[i].color,
                        });
                    }

                }
            });
            return myData;
        }

 var calendar = $('#calendar').calendar({
                dataSource: getMyData(),
                startYear: 2016,
                allowOverlap: true,
                enableRangeSelection: true,
                mouseOnDay: function (e) {
                    if (e.events.length > 0) {
                        var content = '';

                        for (var i in e.events) {
                            content += '<div class="event-tooltip-content">'
                                            + '<div class="event-name" style="color:' + e.events[i].color + '">' + e.events[i].name + '</div>'   +'</div>';
                        }

                        $(e.element).popover({
                            trigger: 'manual',
                            container: 'body',
                            html: true,
                            content: content
                        });

                        $(e.element).popover('show');
                    }
                },
                mouseOutDay: function (e) {
                    if (e.events.length > 0) {
                        $(e.element).popover('hide');
                    }
                },
                dayContextMenu: function (e) {
                    $(e.element).popover('hide');
                }

            });

        });
```

This is not the only binding method I used, I used many but still facing the same issue. Please help and guide.

**Comment by palnmathur** [comment]
Please anyone reply .. I really need to done this ASAP.

**Comment by Paul-DS** [comment]
There is 2 problems in your code:
- The first one is the method used for binding the data source, the calendar expect an array in the `datasource` option, so you cannot pass a function. You can check the issue #21 for the implementation of an AJAX datasource.
- The second problem is your AJAX request. You code is built like a sequencial code, but the AJAX call in your case is asynchronous (the `async `parameter is set to `true` by default). You need to set the datasource of the calendar in the `success` event of the AJAX call.

So the code should be as following:

	var calendar = $('#calendar').calendar({
		yearChanged: function(e) {
			e.preventRendering = true;

			$(e.target).append('<div style="text-align:center"><img src="your-loading-image.gif" /></div>');

			$.ajax({ 
				url: "Index/holiday", 
				success: function(response) {
					var myData = [];
					for (var i = 0; i < response.length; i++) {
						myData.push({
							id: response[i].id,
							title: response[i].title,
							startDate: new Date(response[i].startDate),
							endDate: new Date(response[i].endDate),
							color: response[i].color,
						});
					}

					$(e.target).data('calendar').setDataSource(myData);
				} 
			});
		}
	});

**Comment by palnmathur** [comment]
thank you so much for reply .. I will apply this. I have some more requirements, please share if possible to apply : 
1. Can I show the calendar from months to months .. for example a financial year .. it includes months of 2 years .. March 2016 to April 2017.  

2. Can I show few months in a year .. like .. April to Oct only ..

3. Can I disable all dates but the dates on my dataSource (my holidays).

Please share if possible, and if yes that how.

Thanks in advance.
NMathur

**Comment by Paul-DS** [comment]
> 1. Can I show few months in a year .. like .. April to Oct only ..

There is no such functionality out of the box, but this has already been done, check issue #18.

> 2. Can I disable all dates but the dates on my dataSource (my holidays).

You can use a workaround by tagging all the days of your datasource and disabling all the days that are not tagged after setting the datasource:
- In your customDataSourceRenderer:
```
customDataSourceRenderer: function(elt, date, events) {
    $(elt).addClass('has-data-source');
}
```

- And after the `setDataSource(myData)`:
```
$('td.day:not([has-data-source]').addClass('disabled')
```

**Comment by palnmathur** [comment]
same issue .. when I load page first time .. holidays are not reflecting on calendar .. changing years was already working .. after changing years the holidays were showing with their color .. the issue is occurring when first time I go to page ..

**Comment by Paul-DS** [comment]
Could you share your javascript code for the calendar initialization ?

**Comment by palnmathur** [comment]
I have prepared a sample .. let me share with you .. 

My View:

`@{
    ViewBag.Title = "Home Page";
}

<link href="~/css/bootstrap-year-calendar.css" rel="stylesheet" />
<div id="calendar"></div>
@section Scripts{
<script src="~/js/bootstrap-year-calendar.js"></script>

<script>
    $(function () {
        var currentYear = new Date().getFullYear();

        $('#calendar').calendar({
            enableContextMenu: true,
            enableRangeSelection: true,
            style:"background",   
            dataSource: $.ajax({
                url: '@Url.Action("Calendar", "Home")',
                success: function (data) {
                    return data;
                }
            })
        });
    });
</script>
    }`

My Code:
`public JsonResult Calendar()
        {
            TestArray[] me = new TestArray[5];
            
            me[0] = new TestArray();
            me[0].id = 0;
            me[0].name = "Google 1";
            me[0].location = "San Francisco, 1";
            me[0].startDate = DateTime.Now.AddDays(4);
            me[0].endDate = DateTime.Now.AddDays(8);
            me[0].color = "#0f0f0f";


            me[1] = new TestArray();
            me[1].id = 1;
            me[1].name = "Google 2";
            me[1].location = "San Francisco, 2";
            me[1].startDate = DateTime.Now.AddDays(20);
            me[1].endDate = DateTime.Now.AddDays(20);
            me[1].color = "#0f0f0f";

            me[2] = new TestArray();
            me[2].id = 2;
            me[2].name = "Google 3";
            me[2].location = "San Francisco, 3";
            me[2].startDate = DateTime.Now.AddDays(40);
            me[2].endDate = DateTime.Now.AddDays(45);
            me[2].color = "#0f0f0f";

            me[3] = new TestArray();
            me[3].id =3;
            me[3].name = "Google 4";
            me[3].location = "San Francisco, 41";
            me[3].startDate = DateTime.Now.AddDays(60);
            me[3].endDate = DateTime.Now.AddDays(61);
            me[3].color = "#0f0f0f";

            me[4] = new TestArray();
            me[4].id =4 ;
            me[4].name = "Google 5";
            me[4].location = "San Francisco, 5";
            me[4].startDate = DateTime.Now.AddDays(66);
            me[4].endDate = DateTime.Now.AddDays(69);
            me[4].color = "#0f0f0f";
            
            var retVal = Json(me, JsonRequestBehavior.AllowGet);
            return retVal;
        }
           
    }

    //array class 
    public class TestArray
    {
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
        public string color { get; set; }
    }`

I was very hopeful that this will defiantly work .. but its not working .. 

also tried .. my view
`  $(function () {
        var currentYear = new Date().getFullYear();

        $('#calendar').calendar({
            enableContextMenu: true,
            enableRangeSelection: true,
            style:"background",   
            dataSource:  '@Url.Action("Calendar", "Home")'           
        });
    });`

I am not getting it .. I am sure it is because of a minor mistake :( .. hope you can help.

**Comment by Paul-DS** [comment]
This is not the implementation that I show you before ?
You are currently passing an url in the `dataSource` options, which should be an array of elements.

Try with this client code:

```
$(function () {
    var currentYear = new Date().getFullYear();

    $('#calendar').calendar({
        enableContextMenu: true,
        enableRangeSelection: true,
        style:"background",
		customDataSourceRenderer: function(elt, date, events) {
			$(elt).addClass('has-data-source');
		},
        yearChanged: function(e) {
			e.preventRendering = true;

			$.ajax({ 
				url: "@Url.Action("Calendar", "Home")", 
				success: function(response) {
					var myData = [];
					for (var i = 0; i < response.length; i++) {
						myData.push({
							id: response[i].id,
							title: response[i].title,
							startDate: new Date(response[i].startDate),
							endDate: new Date(response[i].endDate),
							color: response[i].color,
						});
					}

					$(e.target).data('calendar').setDataSource(myData);
					
					// Disable the day on which there is no events
					$('td.day:not([has-data-source]').addClass('disabled');
				} 
			});
		}
    });
});
```

And check with a debugger in the `success` function of the AJAX call:
- If the `response` object is the object built server side, or if the response is the string representing the JSON of the object (in this case you will have to parse it using `JSON.parse(response)`)
- If the dates passed by the server as correctly parsed in javascript.

**Comment by palnmathur** [comment]
thanks for reply,  I am going to try this code.. hope this will work.

**Comment by palnmathur** [comment]
thanks a lot for the disabled effect .. its awesome.. and the code too. My main issue is that I am not able to pass an an array of elements to dataSource. I don't have much experience .. so not able to create and pass an dynamically created array .. yearChanged is working like a charm .. also the disabled effect .. I have to explore more .. thanks alot for your time .. you are too good bro :) .. god bless you .... god! bless me too :(

**Comment by Paul-DS** [comment]
No problem !

The datasource array is not required. In your case, the calendar is filled by the AJAX request, so you don't have to pass the `datasource` option.

**Comment by palnmathur** [comment]
really !! .. then why the calendar is not showing holidays at first page load .. after changing years it is showing the details .. but not at first load .. this is the main issue . and its driving me crazy .. I am working on it from last 2 days .. finally I decided to ask you for the help.

**Comment by Paul-DS** [comment]
This is not working, even with the code that I gave you ?

**Comment by palnmathur** [comment]
na .. its not .. when I change year . it works.. otherwise .. its not ..

**Comment by Paul-DS** [comment]
You are right, the problem comes from the calendar, sorry.

The `yearChanged` event is not trigerred at initialization. I will fix this problem. For the moment, you can fix it quicky by changing the bootstrap-year-calendar.js file. replace the line 27:
`this.render()` by `this.setYear(options.startYear)`

**Comment by palnmathur** [comment]
THANK YOU !!!!  :) ... you are awesome ... you helped me a lot ... its working now ... thank you so much .. keep up the good work :)

**Comment by elviskudo** [comment]
hi,

your plugins is awesome!
but i have issue here about data from json
still now i cannot connect datasource with my json built with js loop
how can i?
do you got solution?
thanks a lot
