### ISSUE TITLE
Confusing dates

### ISSUE THREAD

**Issue by gtusar** [Paul-DS/bootstrap-year-calendar#58]
Hi. 
I have some troubles with using this calendar.
After inserting a date into a event array, the event is inserted with wrong month. It misses one month. 
http://i63.tinypic.com/5tz8rq.png

I also noticed a problem with week numbers. So you can see on the example page, that the week number starts only from second week in year.
http://i65.tinypic.com/2ds0m8h.png

Am I maybe doing something wrong?

**Comment by gtusar** [comment]
Sorry for this.
Figured out both issues. 
First one with missing month. I found out that javascript month is [zero-based (0-11).](http://stackoverflow.com/a/1507625/4251385)

The other problem was magically solved in my real application.

Beside, I can post here a Slovenian translation also if you are willing to integrate it:
` sl: {
        days: ["Nedelja", "Ponedeljek", "Torek", "Sreda", "Četrtek", "Petek", "Sobota", "Nedelja"],
        daysShort: ["Ned", "Pon", "Tor", "Sre", "Čet", "Pet", "Sob", "Ned"],
        daysMin: ["Ne", "Po", "To", "Sr", "Če", "Pe", "So", "Ne"],
        months: ["Januar", "Februar", "Marec", "April", "Maj", "Junij", "Julij", "Avgust", "September", "Oktober", "November", "December"],
        monthsShort: ["Jan", "Feb", "Mar", "Apr", "Maj", "Jun", "Jul", "Avg", "Sep", "Okt", "Nov", "Dec"],
        weekShort: 'T',
        weekStart: 1
    }`

Thanks, bye!

**Comment by skizzy** [comment]
How do you configure the months to read from 1 instead of 0? I'm facing same issue with javascript

**Comment by gtusar** [comment]
This is javascript problem. Months are zero-based, this means January is 0 February is 1 and so on. When you create event you need to have in mind that when passing it to start and end date Date object.
