### ISSUE TITLE
Config Months to View

### ISSUE THREAD

**Issue by pedrocortizo** [Paul-DS/bootstrap-year-calendar#60]
Hi, thx for mthis excellent project

This issue is most a feature-request. 

As the fork made by @taniarv, 
https://github.com/taniarv/bootstrap-year-calendar/commit/5d82ef0b54b4e99e9448efa891438a0a2a5cee63

I need an option that permits to show only the months between startDate and endDate. The problem with Tania's solution are the events. The calendar only shows the events of the current year, so if you have a view with moths of two years, like the screen shoot, only view the events for current year.

In this case, we need a solution to unlimit this feature. If you can guide me about the portion of code to modify and get the events for all visible months, I will be really grateful

Thanks!

![2016-10-17_11-29-36](https://cloud.githubusercontent.com/assets/5601879/19432521/2cf0c4ee-945d-11e6-84d0-8b8c86859a86.jpg)
![2016-10-17_11-29-49](https://cloud.githubusercontent.com/assets/5601879/19432522/2d03415a-945d-11e6-8bcf-daef3e94ae1a.jpg)

**Comment by Paul-DS** [comment]
I know this thread is pretty old, but I'm working on this feature in the new version of the library: [js-year-calendar](https://github.com/year-calendar/js-year-calendar)
You can follow the development (and test the functionality) in the PR year-calendar/js-year-calendar#32

**Comment by Paul-DS** [comment]
The feature is available in js-year-calendar@v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
