### ISSUE TITLE
Days 30 and 31 not showing color (ASP Net WebForms)

### ISSUE THREAD

**Issue by William-H-M** [Paul-DS/bootstrap-year-calendar#74]
First than all thanks for such amazing script quite simple to use for my needs...

When first loading the calendar every date with their events loads as expected with just the incovenient that is not rendering correctly the color for days 30 and 31 for december and sometimes for november or the other months having 30, 31

![captura de pantalla 18](https://cloud.githubusercontent.com/assets/24443241/20989931/997f8a68-bca4-11e6-880a-ae10b309b63e.png)

![captura de pantalla 19](https://cloud.githubusercontent.com/assets/24443241/20989934/9c6cca1a-bca4-11e6-94ae-27940c311df0.png)

On first load it doesn't show it but if I change the year and then get back again to current year it'll show as expected.

I've tried doing a calendar change from codebehind, but was not possible and tried #53  solution but it doesn't work as the same for me (Just work If I change of year and the get back to current) ; another workaround I been thinking is that on load of calendar do a click to next year and then get back again to current year or just use initialYear as currentYear + 1 and then get it back to currentYear

If possible if anyone else know of a better way to solve this? Even when is not a serious problem can be confusing for users thanks in advance for any solution that can be granted.

**Comment by William-H-M** [comment]
I've found an simple work around for this that will work for pepole, mainly using webforms and that don't want, or don't know hot to use Ajax, the workaround is quite simple.

1) Do the change suggested by @swordsman77 on issue #53
2) Load the calendar as usual but with the exception that the startYear will be currentYear + 1 and then with a setTimeout function set it again to currentYear you can do the same with a click function prev tag so it'll end to something like this:

![captura de pantalla 21](https://cloud.githubusercontent.com/assets/24443241/21051451/463a2e08-bdee-11e6-9070-9425d2f99153.png)

The reason that It doesn't work from start the solution given on #53 is because my datasource is not loaded by ajax but from an array loaded from codebehind.

If any doubt is presented feel free to re-open this issue.

**Comment by Lazaaa** [comment]
`<script>
  $('#event-modal input[name="event-start-date"]').datepicker({
    daysOfWeekDisabled:[7,0],
    language: 'hu',
    startDate: "dateToday",
    autoclose: true
  });
  $('#event-modal input[name="event-end-date"]').datepicker({
    daysOfWeekDisabled:[7,0],
    language: 'hu',
    startDate: "dateToday",
    autoclose: true
  });
  
  $('#event-modal [name="event-name"]').change(function () {
    $('#event-modal #szin').css('background',$('#event-modal [name="event-name"]').val());
  });
  
  function datum(date) {
    var year = date.getFullYear();
    var month = (1 + date.getMonth()).toString();
    month = month.length > 1 ? month : '0' + month;
    var day = date.getDate().toString();
    day = day.length > 1 ? day : '0' + day;
    return  year + '-'+month + '-' + day;
  }
  
  function editEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert('Visszamenőleg nem lehet beírni, módosítani vagy törölni!');
      return;
    };
    if (event.id){
      $('#event-modal input[name="event-index"]').val(event.id);
      $('#event-modal [name="event-name"]').val(event.color);
      $('#event-modal #szin').css('background',event.color);
      $('#event-modal input[name="event-start-date"]').datepicker('update', event ? event.startDate : '');
      $('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.endDate : '');
    }else {
      $('#event-modal input[name="event-index"]').val('');
      $('#event-modal input[name="event-name"]').val('');
      $('#event-modal input[name="event-start-date"]').datepicker('update', event ? event.startDate : '');
      $('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.endDate : '');
    }
    $('#event-modal').modal();
  }

  
  function workingDaysBetweenDates(startDate, endDate) {
    var millisecondsPerDay = 86400 * 1000; 
    startDate.setHours(0,0,0,1);
    endDate.setHours(23,59,59,999);
    var diff = endDate - startDate;
    var days = Math.ceil(diff / millisecondsPerDay);
    var weeks = Math.floor(days / 7);
    days = days - (weeks * 2);
    var startDay = startDate.getDay();
    var endDay = endDate.getDay();
    if (startDay - endDay > 1)
        days = days - 2;
    if (startDay === 0 && endDay != 7)
        days = days - 1 ; 
    if (endDay === 6 && startDay !== 0)
        days = days - 1  ;
    return days;
  };
  
  function deleteEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert('Visszamenőleg nem lehet beírni, módosítani vagy törölni!');
      return;
    };
    $.ajax({ 
      url: 'szabiadatok.php',
      type: 'GET',
      data: 'type=delete&id='+event.id,
      success: function(response) {
        alert(response);
      } 
    });
    $('#calendar').data('calendar').setDataSource(dataSource);
  }

  function saveEvent() {
    var event = {
      id: $('#event-modal input[name="event-index"]').val(),
      name: $('#event-modal select[name="event-name"] option:selected').text(),
      color: $('#event-modal select[name="event-name"] option:selected').val(),
      startDate: $('#event-modal input[name="event-start-date"]').datepicker('getDate'),
      endDate: $('#event-modal input[name="event-end-date"]').datepicker('getDate')
    }
    var days = workingDaysBetweenDates(event.startDate, event.endDate);
    var dataSource = $('#calendar').data('calendar').getDataSource();

    if(event.id) {
      $.ajax({ 
        url: 'szabiadatok.php',
        type: 'GET',
        data: 'type=update&id='+event.id+'&startDate='+datum(event.startDate)+'&endDate='+datum(event.endDate)+'&days='+days,
        success: function(response) {
          alert(response);
        } 
      });
    }else{
      $.ajax({ 
        url: 'szabiadatok.php',
        type: 'GET',
        data: 'type=add&startDate='+datum(event.startDate)+'&endDate='+datum(event.endDate)+'&days='+days+'&title='+event.name+'&color='+event.color.substring(1, 7),
        success: function(response) {
          alert(response);
        } 
      });
    }
    $('#calendar').data('calendar').setDataSource(dataSource);
    $('#event-modal').modal('hide');
  }

$(function() {
    var currentYear = new Date().getFullYear();
    $('#calendar').calendar({
        minDate: new Date('2016-01-01'),
        disabledWeekDays: [7, 0],
        language: 'hu',
        style: 'border',
        yearChanged: function(e) {
          $.ajax({ 
            url: 'szabiadatok.php',
            type: 'GET',
            data: 'type=lekerdezes&ev='+$('#calendar').data('calendar').getYear(),
            success: function(response) {
              $("#lista").html(response);
            }
          });
          var d = new Date();
          var ho = d.getMonth()+1;
          $.ajax({ 
            url: 'szabiadatok.php',
            type: 'GET',
            data: 'type=aktualishonap&ev='+d.getFullYear()+'&honap='+ho,
            success: function(response) {
              $("#aktualis").html(response);
            }
          });
          e.preventRendering = true;
          var dataSource=[];
          $.ajax({ 
            url: 'szabiadatok.php',
            type: 'GET',
            dataType: 'json',
            data: 'type=fetch',
            success: function(response) {
              console.log(response);
              for (var i = 0; i < response.length; i++) {
                dataSource.push({
                  id: response[i].id,
                  name: response[i].title,
                  startDate: new Date(response[i].start),
                  endDate: new Date(response[i].end),
                  color: response[i].backgroundColor
                });
              }
              $('#calendar').data('calendar').setDataSource(dataSource);
            } 
          });
        },
        allowOverlap: true,
        enableContextMenu: true,
        enableRangeSelection: true,
        contextMenuItems:
          [{
              text: 'Módosítás',
              click: editEvent
            },
            {
              text: 'Törlés',
              click: deleteEvent
            }
          ],
        selectRange: function(e) {
          editEvent({ startDate: e.startDate, endDate: e.endDate });
        },
        mouseOnDay: function(e) {
          if(e.events.length > 0) {
            var content = '';
            for(var i in e.events) {
              content += '<div class="event-tooltip-content">'
                        + '<div class="event-name" style="color:' + e.events[i].color + ';">' + e.events[i].name +'</div>'
                      + '</div>';
            }
            $(e.element).popover({ 
              trigger: 'manual',
              container: 'body',
              html:true,
              content: content
            });
            $(e.element).popover('show');
          }
        },
        mouseOutDay: function(e) {
          if(e.events.length > 0) {
            $(e.element).popover('hide');
          }
        },
        dayContextMenu: function(e) {
          $(e.element).popover('hide');
        }
    });
    
    $('#save-event').click(function() {
      saveEvent();
    });
});
</script>`
