### ISSUE TITLE
Month container covering another one on top

### ISSUE THREAD

**Issue by gtusar** [Paul-DS/bootstrap-year-calendar#77]
Hi.
Very nice work with your calendar! I love it.

I just have a problem, which I can't solve.
The problem is that a month name is covering last days of the month above. And therefore the days are not clickable. Is there a solution for that?
![issue](https://cloud.githubusercontent.com/assets/18527163/21228662/f32b10ec-c2de-11e6-9782-01e9cf329be1.PNG)

**Comment by gtusar** [comment]
Ok, solved by setting "margin-top" to class "month-container".

**Comment by William-H-M** [comment]
This usually happen if screen size given to calendar is medium otherwise won't happen but quite the good and simple fix.

Please close this issue as is solved.
