### ISSUE TITLE
Event dates with time information don't work

### ISSUE THREAD

**Issue by gtusar** [Paul-DS/bootstrap-year-calendar#78]
Hello again,
I am pulling my hair out, because of the problems with startDate and endDate for events.
If I add time data into "new Date()" function, the event does not show in calendar.
Is the only way to get over this with using a kind of temporary date values?
Thank you

**Comment by William-H-M** [comment]
Hi again, can you provide us an example on how are you setting dates? an what programing language you're using that way it'll easier.

But just asuming probably the problem is how you're setting the date with javascript

**Comment by gtusar** [comment]
Hi,
I am using ASP MVC with Razor engine.
Here is the command which inserts event into table:
This works:
```
@:intrinsicEvents.push(
{
 id:@e.Id,
 name:'@e.WorkTask.TaskType.Name', 
 duration:@duration,
 description:'@e.Description', 
 startDate: new Date(@e.DateStart.Year,@(e.DateStart.Month-1), @e.DateStart.Day), 
 endDate: new Date(@endD.Year, @(endD.Month-1), @endD.Day), 
 approved:@Json.Encode(e.Approved) 
});
```
This does NOT work:
```
@:intrinsicEvents.push(
{
 id:@e.Id,
 name:'@e.WorkTask.TaskType.Name', 
 duration:@duration,
 description:'@e.Description', 
 startDate: new Date(@e.DateStart.Year,@(e.DateStart.Month-1), @e.DateStart.Day, @e.DateStart.Hour, @e.DateStart.Minute), 
 endDate: new Date(@endD.Year, @(endD.Month-1), @endD.Day, @endD.Hour, @endD.Minute), 
 approved:@Json.Encode(e.Approved) 
});
```
I tried also with adding milliseconds, but it also fails.

**Comment by William-H-M** [comment]
That's weird... You have all in correct format as It should be done in MVC I have it in aspx AJAX and it should be the same...
This would sound kinda stupid but try to do a parseInt on hour and on minute or somehting like this 
![captura](https://cloud.githubusercontent.com/assets/24443241/21264267/5f1d4a9c-c369-11e6-99da-95d596e8fe22.PNG)

If it's doesn't work the I don't really what could it be but maybe it's just a simple problem and not a bug.
Good luck

**Comment by gtusar** [comment]
I just found out what is the problem. 
If the event just a few hours long, i.e. the date part is the same, only time part is different, the calendar won't show the event.
So this will not appear on calendar:
```
 startDate: new Date(2016,9,15, 2,10)
 endDate:  new Date(2016,9,15, 15,16)
```
Meanwhile this, will:
```
 startDate: new Date(2016,9,15, 0,0)
 endDate:  new Date(2016,9,15, 0,0)
```
And this will only mark one day:
```
                startDate: new Date(2016,9,15,2,0)
                endDate: new Date(2016,9,16,22,0)
```
Is there a way to mark all affected days?

**Comment by William-H-M** [comment]
That's weird is just used your example for start and end date and still marked as it should do it...
But if you see on my next image the time part is 00:00:00 
![test](https://cloud.githubusercontent.com/assets/24443241/21266221/0f7f2a00-c373-11e6-9404-d20d6f89446c.png)
What you should do is set as your first workaround with:

`@:intrinsicEvents.push(
{
 id:@e.Id,
 name:'@e.WorkTask.TaskType.Name', 
 duration:@duration,
 description:'@e.Description', 
 startDate: new Date(@e.DateStart.Year,@(e.DateStart.Month-1), @e.DateStart.Day), 
 endDate: new Date(@endD.Year, @(endD.Month-1), @endD.Day), 
 approved:@Json.Encode(e.Approved) 
});`

Then probably what you want to do is show date and time of the event start for that just do something like:

` StrtHour: @e.DateStart.Hour + ':' + @e.DateStart.Minute,    
                        EndHour: @endD.Hour + ':' + @endD.Minute, 
                        "Same for Dates..."
 `        
Maybe not the best practice but it'll will work for a calendar

**Comment by gtusar** [comment]
Well hello there again.
My brains got some refreshment this weekend, so I was able to find the solution for my problem this morning. :)

The root of the problem is date comparison in date rendering part of code. 
The command states:
```
if(monthData[i].startDate <= currentDate && monthData[i].endDate >= currentDate) 
{
      dayData.push(monthData[i]);										
}
```
So if the `startDate `has TIME part, this statement is always FALSE, so the event is not inserted in dayData array.
The `endDate` is not problematic, because even with Time part is always bigger or equal to `currentDate`.

So the solution is here:
I source file `bootstrap-year-calendar.js` in function `_renderDataSource  `**(row 330)** I added a new date variable which is a `clone` of `startDate `. Then I assign hours, minutes and seconds equal to 0. Then we compare the the dates.
```
var _tmpStartDate = new Date(monthData[i].startDate.getTime());
_tmpStartDate.setHours(0, 0, 0);
if (_tmpStartDate <= currentDate && monthData[i].endDate >= currentDate) {
	dayData.push(monthData[i]);
}
```
Because the code has another similar date check to apply events, I also added equal code to function `getEvents `**(row 777)** : 
```
var _tmpStartDate = new Date(this.options.dataSource[i].startDate.getTime());
_tmpStartDate.setHours(0, 0, 0);
if (_tmpStartDate <= date && this.options.dataSource[i].endDate >= date) {
	events.push(this.options.dataSource[i]);
}
```

So the code works as I wanted now, the time part is included in startDate and endDate properties of each event. So I don't need to add additional properties which carry only time information and the most  important thing is that the datetime pickers are working and getting and returning the correct data without any other code change to original examples.

Thank you for help William, I hope that this helps anyone ;)

Cheers!

**Comment by William-H-M** [comment]
Great you should put this as a pull that way could be solved for all of us if happen again!
As this seems to be solver please close this that way other will find this more helpful as they will now is fixed your problem, and may they are facing the same.
Good Luck and  if anything need it, I'll try to help

**Comment by gtusar** [comment]
Will do that soon.
Thanks.
