### ISSUE TITLE
event border style problem

### ISSUE THREAD

**Issue by Lazaaa** [Paul-DS/bootstrap-year-calendar#79]
If event in line 6 don't render box-shadow.

![capture](https://cloud.githubusercontent.com/assets/8706514/21346029/e2a68f04-c6a2-11e6-8c99-884a28d24960.JPG)

**Comment by William-H-M** [comment]
If I'm not wrong your problem is that the line that show that there's an event on that day is not showing right?
Something like this:
![captura de pantalla 18](https://cloud.githubusercontent.com/assets/24443241/21355628/c0255df8-c69c-11e6-845e-a71ad8b219b9.png)

If that the case please refer to issue #53 and #74

**Comment by Lazaaa** [comment]
not working #53!

**Comment by William-H-M** [comment]
Did you did the changes on #74 too? because if you don't is probably that happen, the reason is that the ajax call sometimes is not recognised, if not working either then please provide us a sample code on how are you filling DataSource so that way we could find a solution

**Comment by Lazaaa** [comment]
Sure i try it, but not woking.

here is a code:

2016-12-21 17:45 GMT+01:00 William-H-M <notifications@github.com>:

**Comment by Lazaaa** [comment]
`<script>
  $("#event-modal input[name="event-start-date"]").datepicker({
    daysOfWeekDisabled:[7,0],
    language: "hu",
    startDate: "dateToday",
    autoclose: true
  });
  $("#event-modal input[name="event-end-date"]").datepicker({
    daysOfWeekDisabled:[7,0],
    language: "hu",
    startDate: "dateToday",
    autoclose: true
  });
  
  $("#event-modal [name="event-name"]").change(function () {
    $("#event-modal #szin").css("background",$("#event-modal [name="event-name"]").val());
  });
  
  function datum(date) {
    var year = date.getFullYear();
    var month = (1 + date.getMonth()).toString();
    month = month.length > 1 ? month : "0" + month;
    var day = date.getDate().toString();
    day = day.length > 1 ? day : "0" + day;
    return  year + "-"+month + "-" + day;
  }
  
  function editEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert("Visszamenőleg nem lehet beírni, módosítani vagy törölni!");
      return;
    };
    if (event.id){
      $("#event-modal input[name="event-index"]").val(event.id);
      $("#event-modal [name="event-name"]").val(event.color);
      $("#event-modal #szin").css("background",event.color);
      $("#event-modal input[name="event-start-date"]").datepicker("update", event ? event.startDate : "");
      $("#event-modal input[name="event-end-date"]").datepicker("update", event ? event.endDate : "");
    }else {
      $("#event-modal input[name="event-index"]").val("");
      $("#event-modal input[name="event-name"]").val("");
      $("#event-modal input[name="event-start-date"]").datepicker("update", event ? event.startDate : "");
      $("#event-modal input[name="event-end-date"]").datepicker("update", event ? event.endDate : "");
    }
    $("#event-modal").modal();
  }

  
  function workingDaysBetweenDates(startDate, endDate) {
    var millisecondsPerDay = 86400 * 1000; 
    startDate.setHours(0,0,0,1);
    endDate.setHours(23,59,59,999);
    var diff = endDate - startDate;
    var days = Math.ceil(diff / millisecondsPerDay);
    var weeks = Math.floor(days / 7);
    days = days - (weeks * 2);
    var startDay = startDate.getDay();
    var endDay = endDate.getDay();
    if (startDay - endDay > 1)
        days = days - 2;
    if (startDay === 0 && endDay != 7)
        days = days - 1 ; 
    if (endDay === 6 && startDay !== 0)
        days = days - 1  ;
    return days;
  };
  
  function deleteEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert("Visszamenőleg nem lehet beírni, módosítani vagy törölni!");
      return;
    };
    $.ajax({ 
      url: "szabiadatok.php",
      type: "GET",
      data: "type=delete&id="+event.id,
      success: function(response) {
        alert(response);
      } 
    });
    $("#calendar").data("calendar").setDataSource(dataSource);
  }

  function saveEvent() {
    var event = {
      id: $("#event-modal input[name="event-index"]").val(),
      name: $("#event-modal select[name="event-name"] option:selected").text(),
      color: $("#event-modal select[name="event-name"] option:selected").val(),
      startDate: $("#event-modal input[name="event-start-date"]").datepicker("getDate"),
      endDate: $("#event-modal input[name="event-end-date"]").datepicker("getDate")
    }
    var days = workingDaysBetweenDates(event.startDate, event.endDate);
    var dataSource = $("#calendar").data("calendar").getDataSource();

    if(event.id) {
      $.ajax({ 
        url: "szabiadatok.php",
        type: "GET",
        data: "type=update&id="+event.id+"&startDate="+datum(event.startDate)+"&endDate="+datum(event.endDate)+"&days="+days,
        success: function(response) {
          alert(response);
        } 
      });
    }else{
      $.ajax({ 
        url: "szabiadatok.php",
        type: "GET",
        data: "type=add&startDate="+datum(event.startDate)+"&endDate="+datum(event.endDate)+"&days="+days+"&title="+event.name+"&color="+event.color.substring(1, 7),
        success: function(response) {
          alert(response);
        } 
      });
    }
    $("#calendar").data("calendar").setDataSource(dataSource);
    $("#event-modal").modal("hide");
  }

$(function() {
    var currentYear = new Date().getFullYear();
    $("#calendar").calendar({
        minDate: new Date("2016-01-01"),
        disabledWeekDays: [7, 0],
        language: "hu",
        style: "border",
        yearChanged: function(e) {
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            data: "type=lekerdezes&ev="+$("#calendar").data("calendar").getYear(),
            success: function(response) {
              $("#lista").html(response);
            }
          });
          var d = new Date();
          var ho = d.getMonth()+1;
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            data: "type=aktualishonap&ev="+d.getFullYear()+"&honap="+ho,
            success: function(response) {
              $("#aktualis").html(response);
            }
          });
          e.preventRendering = true;
          var dataSource=[];
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            dataType: "json",
            data: "type=fetch",
            success: function(response) {
              console.log(response);
              for (var i = 0; i < response.length; i++) {
                dataSource.push({
                  id: response[i].id,
                  name: response[i].title,
                  startDate: new Date(response[i].start),
                  endDate: new Date(response[i].end),
                  color: response[i].backgroundColor
                });
              }
              $("#calendar").data("calendar").setDataSource(dataSource);
            } 
          });
        },
        allowOverlap: true,
        enableContextMenu: true,
        enableRangeSelection: true,
        contextMenuItems:
          [{
              text: "Módosítás",
              click: editEvent
            },
            {
              text: "Törlés",
              click: deleteEvent
            }
          ],
        selectRange: function(e) {
          editEvent({ startDate: e.startDate, endDate: e.endDate });
        },
        mouseOnDay: function(e) {
          if(e.events.length > 0) {
            var content = "";
            for(var i in e.events) {
              content += "<div class="event-tooltip-content">"
                        + "<div class="event-name" style="color:" + e.events[i].color + ";">" + e.events[i].name +"</div>"
                      + "</div>";
            }
            $(e.element).popover({ 
              trigger: "manual",
              container: "body",
              html:true,
              content: content
            });
            $(e.element).popover("show");
          }
        },
        mouseOutDay: function(e) {
          if(e.events.length > 0) {
            $(e.element).popover("hide");
          }
        },
        dayContextMenu: function(e) {
          $(e.element).popover("hide");
        }
    });
    
    $("#save-event").click(function() {
      saveEvent();
    });
});
</script>`

**Comment by Lazaaa** [comment]
<script>
  $("#event-modal input[name="event-start-date"]").datepicker({
    daysOfWeekDisabled:[7,0],
    language: "hu",
    startDate: "dateToday",
    autoclose: true
  });
  $("#event-modal input[name="event-end-date"]").datepicker({
    daysOfWeekDisabled:[7,0],
    language: "hu",
    startDate: "dateToday",
    autoclose: true
  });
  
  $("#event-modal [name="event-name"]").change(function () {
    $("#event-modal #szin").css("background",$("#event-modal [name="event-name"]").val());
  });
  
  function datum(date) {
    var year = date.getFullYear();
    var month = (1 + date.getMonth()).toString();
    month = month.length > 1 ? month : "0" + month;
    var day = date.getDate().toString();
    day = day.length > 1 ? day : "0" + day;
    return  year + "-"+month + "-" + day;
  }
  
  function editEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert("Visszamenőleg nem lehet beírni, módosítani vagy törölni!");
      return;
    };
    if (event.id){
      $("#event-modal input[name="event-index"]").val(event.id);
      $("#event-modal [name="event-name"]").val(event.color);
      $("#event-modal #szin").css("background",event.color);
      $("#event-modal input[name="event-start-date"]").datepicker("update", event ? event.startDate : "");
      $("#event-modal input[name="event-end-date"]").datepicker("update", event ? event.endDate : "");
    }else {
      $("#event-modal input[name="event-index"]").val("");
      $("#event-modal input[name="event-name"]").val("");
      $("#event-modal input[name="event-start-date"]").datepicker("update", event ? event.startDate : "");
      $("#event-modal input[name="event-end-date"]").datepicker("update", event ? event.endDate : "");
    }
    $("#event-modal").modal();
  }

  
  function workingDaysBetweenDates(startDate, endDate) {
    var millisecondsPerDay = 86400 * 1000; 
    startDate.setHours(0,0,0,1);
    endDate.setHours(23,59,59,999);
    var diff = endDate - startDate;
    var days = Math.ceil(diff / millisecondsPerDay);
    var weeks = Math.floor(days / 7);
    days = days - (weeks * 2);
    var startDay = startDate.getDay();
    var endDay = endDate.getDay();
    if (startDay - endDay > 1)
        days = days - 2;
    if (startDay === 0 && endDay != 7)
        days = days - 1 ; 
    if (endDay === 6 && startDay !== 0)
        days = days - 1  ;
    return days;
  };
  
  function deleteEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert("Visszamenőleg nem lehet beírni, módosítani vagy törölni!");
      return;
    };
    $.ajax({ 
      url: "szabiadatok.php",
      type: "GET",
      data: "type=delete&id="+event.id,
      success: function(response) {
        alert(response);
      } 
    });
    $("#calendar").data("calendar").setDataSource(dataSource);
  }

  function saveEvent() {
    var event = {
      id: $("#event-modal input[name="event-index"]").val(),
      name: $("#event-modal select[name="event-name"] option:selected").text(),
      color: $("#event-modal select[name="event-name"] option:selected").val(),
      startDate: $("#event-modal input[name="event-start-date"]").datepicker("getDate"),
      endDate: $("#event-modal input[name="event-end-date"]").datepicker("getDate")
    }
    var days = workingDaysBetweenDates(event.startDate, event.endDate);
    var dataSource = $("#calendar").data("calendar").getDataSource();

    if(event.id) {
      $.ajax({ 
        url: "szabiadatok.php",
        type: "GET",
        data: "type=update&id="+event.id+"&startDate="+datum(event.startDate)+"&endDate="+datum(event.endDate)+"&days="+days,
        success: function(response) {
          alert(response);
        } 
      });
    }else{
      $.ajax({ 
        url: "szabiadatok.php",
        type: "GET",
        data: "type=add&startDate="+datum(event.startDate)+"&endDate="+datum(event.endDate)+"&days="+days+"&title="+event.name+"&color="+event.color.substring(1, 7),
        success: function(response) {
          alert(response);
        } 
      });
    }
    $("#calendar").data("calendar").setDataSource(dataSource);
    $("#event-modal").modal("hide");
  }

$(function() {
    var currentYear = new Date().getFullYear();
    $("#calendar").calendar({
        minDate: new Date("2016-01-01"),
        disabledWeekDays: [7, 0],
        language: "hu",
        style: "border",
        yearChanged: function(e) {
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            data: "type=lekerdezes&ev="+$("#calendar").data("calendar").getYear(),
            success: function(response) {
              $("#lista").html(response);
            }
          });
          var d = new Date();
          var ho = d.getMonth()+1;
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            data: "type=aktualishonap&ev="+d.getFullYear()+"&honap="+ho,
            success: function(response) {
              $("#aktualis").html(response);
            }
          });
          e.preventRendering = true;
          var dataSource=[];
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            dataType: "json",
            data: "type=fetch",
            success: function(response) {
              console.log(response);
              for (var i = 0; i < response.length; i++) {
                dataSource.push({
                  id: response[i].id,
                  name: response[i].title,
                  startDate: new Date(response[i].start),
                  endDate: new Date(response[i].end),
                  color: response[i].backgroundColor
                });
              }
              $("#calendar").data("calendar").setDataSource(dataSource);
            } 
          });
        },
        allowOverlap: true,
        enableContextMenu: true,
        enableRangeSelection: true,
        contextMenuItems:
          [{
              text: "Módosítás",
              click: editEvent
            },
            {
              text: "Törlés",
              click: deleteEvent
            }
          ],
        selectRange: function(e) {
          editEvent({ startDate: e.startDate, endDate: e.endDate });
        },
        mouseOnDay: function(e) {
          if(e.events.length > 0) {
            var content = "";
            for(var i in e.events) {
              content += "<div class="event-tooltip-content">"
                        + "<div class="event-name" style="color:" + e.events[i].color + ";">" + e.events[i].name +"</div>"
                      + "</div>";
            }
            $(e.element).popover({ 
              trigger: "manual",
              container: "body",
              html:true,
              content: content
            });
            $(e.element).popover("show");
          }
        },
        mouseOutDay: function(e) {
          if(e.events.length > 0) {
            $(e.element).popover("hide");
          }
        },
        dayContextMenu: function(e) {
          $(e.element).popover("hide");
        }
    });
    
    $("#save-event").click(function() {
      saveEvent();
    });
});
</script>

**Comment by Lazaaa** [comment]
`<script>
  $("#event-modal input[name="event-start-date"]").datepicker({
    daysOfWeekDisabled:[7,0],
    language: "hu",
    startDate: "dateToday",
    autoclose: true
  });
  $("#event-modal input[name="event-end-date"]").datepicker({
    daysOfWeekDisabled:[7,0],
    language: "hu",
    startDate: "dateToday",
    autoclose: true
  });
  
  $("#event-modal [name="event-name"]").change(function () {
    $("#event-modal #szin").css("background",$("#event-modal [name="event-name"]").val());
  });
  
  function datum(date) {
    var year = date.getFullYear();
    var month = (1 + date.getMonth()).toString();
    month = month.length > 1 ? month : "0" + month;
    var day = date.getDate().toString();
    day = day.length > 1 ? day : "0" + day;
    return  year + "-"+month + "-" + day;
  }
  
  function editEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert("Visszamenőleg nem lehet beírni, módosítani vagy törölni!");
      return;
    };
    if (event.id){
      $("#event-modal input[name="event-index"]").val(event.id);
      $("#event-modal [name="event-name"]").val(event.color);
      $("#event-modal #szin").css("background",event.color);
      $("#event-modal input[name="event-start-date"]").datepicker("update", event ? event.startDate : "");
      $("#event-modal input[name="event-end-date"]").datepicker("update", event ? event.endDate : "");
    }else {
      $("#event-modal input[name="event-index"]").val("");
      $("#event-modal input[name="event-name"]").val("");
      $("#event-modal input[name="event-start-date"]").datepicker("update", event ? event.startDate : "");
      $("#event-modal input[name="event-end-date"]").datepicker("update", event ? event.endDate : "");
    }
    $("#event-modal").modal();
  }

  
  function workingDaysBetweenDates(startDate, endDate) {
    var millisecondsPerDay = 86400 * 1000; 
    startDate.setHours(0,0,0,1);
    endDate.setHours(23,59,59,999);
    var diff = endDate - startDate;
    var days = Math.ceil(diff / millisecondsPerDay);
    var weeks = Math.floor(days / 7);
    days = days - (weeks * 2);
    var startDay = startDate.getDay();
    var endDay = endDate.getDay();
    if (startDay - endDay > 1)
        days = days - 2;
    if (startDay === 0 && endDay != 7)
        days = days - 1 ; 
    if (endDay === 6 && startDay !== 0)
        days = days - 1  ;
    return days;
  };
  
  function deleteEvent(event) {
    var d = new Date();
    var today = d.getFullYear()+ "-" + (d.getMonth()+1) + "-" + (d.getDate());
    if (event.startDate<=new Date(today)){
      alert("Visszamenőleg nem lehet beírni, módosítani vagy törölni!");
      return;
    };
    $.ajax({ 
      url: "szabiadatok.php",
      type: "GET",
      data: "type=delete&id="+event.id,
      success: function(response) {
        alert(response);
      } 
    });
    $("#calendar").data("calendar").setDataSource(dataSource);
  }

  function saveEvent() {
    var event = {
      id: $("#event-modal input[name="event-index"]").val(),
      name: $("#event-modal select[name="event-name"] option:selected").text(),
      color: $("#event-modal select[name="event-name"] option:selected").val(),
      startDate: $("#event-modal input[name="event-start-date"]").datepicker("getDate"),
      endDate: $("#event-modal input[name="event-end-date"]").datepicker("getDate")
    }
    var days = workingDaysBetweenDates(event.startDate, event.endDate);
    var dataSource = $("#calendar").data("calendar").getDataSource();

    if(event.id) {
      $.ajax({ 
        url: "szabiadatok.php",
        type: "GET",
        data: "type=update&id="+event.id+"&startDate="+datum(event.startDate)+"&endDate="+datum(event.endDate)+"&days="+days,
        success: function(response) {
          alert(response);
        } 
      });
    }else{
      $.ajax({ 
        url: "szabiadatok.php",
        type: "GET",
        data: "type=add&startDate="+datum(event.startDate)+"&endDate="+datum(event.endDate)+"&days="+days+"&title="+event.name+"&color="+event.color.substring(1, 7),
        success: function(response) {
          alert(response);
        } 
      });
    }
    $("#calendar").data("calendar").setDataSource(dataSource);
    $("#event-modal").modal("hide");
  }

$(function() {
    var currentYear = new Date().getFullYear();
    $("#calendar").calendar({
        minDate: new Date("2016-01-01"),
        disabledWeekDays: [7, 0],
        language: "hu",
        style: "border",
        yearChanged: function(e) {
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            data: "type=lekerdezes&ev="+$("#calendar").data("calendar").getYear(),
            success: function(response) {
              $("#lista").html(response);
            }
          });
          var d = new Date();
          var ho = d.getMonth()+1;
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            data: "type=aktualishonap&ev="+d.getFullYear()+"&honap="+ho,
            success: function(response) {
              $("#aktualis").html(response);
            }
          });
          e.preventRendering = true;
          var dataSource=[];
          $.ajax({ 
            url: "szabiadatok.php",
            type: "GET",
            dataType: "json",
            data: "type=fetch",
            success: function(response) {
              console.log(response);
              for (var i = 0; i < response.length; i++) {
                dataSource.push({
                  id: response[i].id,
                  name: response[i].title,
                  startDate: new Date(response[i].start),
                  endDate: new Date(response[i].end),
                  color: response[i].backgroundColor
                });
              }
              $("#calendar").data("calendar").setDataSource(dataSource);
            } 
          });
        },
        allowOverlap: true,
        enableContextMenu: true,
        enableRangeSelection: true,
        contextMenuItems:
          [{
              text: "Módosítás",
              click: editEvent
            },
            {
              text: "Törlés",
              click: deleteEvent
            }
          ],
        selectRange: function(e) {
          editEvent({ startDate: e.startDate, endDate: e.endDate });
        },
        mouseOnDay: function(e) {
          if(e.events.length > 0) {
            var content = "";
            for(var i in e.events) {
              content += "<div class="event-tooltip-content">"
                        + "<div class="event-name" style="color:" + e.events[i].color + ";">" + e.events[i].name +"</div>"
                      + "</div>";
            }
            $(e.element).popover({ 
              trigger: "manual",
              container: "body",
              html:true,
              content: content
            });
            $(e.element).popover("show");
          }
        },
        mouseOutDay: function(e) {
          if(e.events.length > 0) {
            $(e.element).popover("hide");
          }
        },
        dayContextMenu: function(e) {
          $(e.element).popover("hide");
        }
    });
    
    $("#save-event").click(function() {
      saveEvent();
    });
});
</script>`

**Comment by William-H-M** [comment]
So I just change a few little things some I haven't see it before so maybe is worng formated and maybe not I just look on the part of the data rendering of   $("#calendar").calendar({...}); The other ones I didn't check up because that's not the problem you are facing I must recomend to just try simple examples and then goind adding the other option to do a check up and see if one of the advanced options is breaking something or the simple one (Just showing events) so this is what I end changing:
PD: the insert code in GitHub do whatever he wants sorry about that...

`$(function() {
    var currentYear = new Date().getFullYear();
              $("#calendar").calendar({
                    minDate: new Date("2016-01-01"),
                    disabledWeekDays: [7, 0], //Here should be [0,6] week start from 0 - 6
                    language: "hu", 
                    //Not sure if this is on current option (No info about it on site change it for: $('#calendar').data('calendar').setLanguage('es'); after calendar options)
                    style: "border",
                
                        yearChanged: function(e) {
                             e.preventRendering = true;//Add this just in case
                            console.log("Year Changed");
                                $.ajax({
                                    url: "szabiadatok.php",
                                    type: "GET",
                                    data: "type=lekerdezes&ev="+$("#calendar").data("calendar").getYear(),
                                    success: function(response) {
                                        $("#lista").html(response);
                                        }             
                                });
                            
                            
                            var d = new Date();
                            var ho = d.getMonth()+1;
                            
                            $.ajax({
                                url: "szabiadatok.php",
                                type: "GET",
                                data: "type=aktualishonap&ev="+d.getFullYear()+"&honap="+ho,
                                success: function(response) {
                                    $("#aktualis").html(response);
                                }
                            });
                            
                            
                            e.preventRendering = true;
                            var dataSource=[];
                            $.ajax({
                                url: "szabiadatok.php",
                                type: "GET",
                                dataType: "json",
                                data: "type=fetch",
                                success: function(response) {
                                    console.log(response);
                                    for (var i = 0; i < response.length; i++) {
                                        dataSource.push({
                                            id: response[i].id,
                                            name: response[i].title,
                                            startDate: new Date(response[i].start),
                                            endDate: new Date(response[i].end),
                                            color: response[i].backgroundColor
                                        });
    
                                    }
    
                                    $("#calendar").data("calendar").setDataSource(dataSource);
                                }
                            });
                            
                        },
                
                allowOverlap: true,
                enableContextMenu: true,
                enableRangeSelection: true,
                contextMenuItems:
                [{
                    text: "Módosítás",
                    click: editEvent
                },
                 {
                     text: "Törlés",
                     text: "Törlés",
                     click: deleteEvent
                 }
                ],
                selectRange: function(e) {
                    editEvent({ startDate: e.startDate, endDate: e.endDate });
                },
                mouseOnDay: function(e) {
                    if(e.events.length > 0) {
                        var content = "";
                        for(var i in e.events) {
                            //wrong formated as you pasted it
                           '<div class="event-tooltip-content">'
                         + '<div class="event-name" style="color:' + e.events[i].color + '">' + e.events[i].name + '</div>' ;
                               
                        }
                    }
                
      $(e.element).popover({
            trigger: 'manual',
            container: 'body',
            html: true,
            content: content
            });

   $(e.element).popover('show');
                
            },
                
      mouseOutDay: function (e) {
                        if (e.events.length > 0) {
                            $(e.element).popover('hide');
                        }
                    },dayContextMenu: function(e) {
$(e.element).popover("hide");
}
            });
    
    $('#calendar').data('calendar').setLanguage('es')//language
          //Fixing rendering issu with a trick and chekind through console.log
                $('#calendar').data('calendar').setYear(currentYear + 1);       
                setTimeout(function() {
                    $('#calendar').data('calendar').setYear(currentYear); 
                    
                }, 0);
    };`


Hope this can help on something

**Comment by Lazaaa** [comment]
I did it, but now does not work. How do you send private to the php files?

**Comment by Lazaaa** [comment]
[szabadsag.txt](https://github.com/Paul-DS/bootstrap-year-calendar/files/668684/szabadsag.txt)
[szabiadatok.txt](https://github.com/Paul-DS/bootstrap-year-calendar/files/668685/szabiadatok.txt)

**Comment by William-H-M** [comment]
Ok checked up 2 things that might seem irrelevant for the rendering but that blew up my calendar
1) look like you're using JQuery 3.1.1 that give problem with bootstrap (this include the extra popover instance) and year calendar, on my app this cause error and do not render or show events.
2) As I understand what you do with the event year changed is do some check data and sum it and add it to a section of your html, and then you set the datasource, please confirm or deny if I'm right.

So for now let's just do the following:

Do not use JQuery 3.1.1 but 2.2.3 just to avoid compability errors, the extra popover maybe is making conflicts with the instance of bootsrap, I doubt it but just in case, so remove it.

set this instance of the data source aout of the $('#calendar').calendar({...})
And do a test out with just the basic example of year calendar, Just make it to show the events do it on other page if possible do not add things like context menu nor add or delete events just show them.


` var dataSource=[];
          $.ajax({ //get year holidays 
            url: "szabiadatok.php",
            type: "GET",
            dataType: "json",
            data: "type=fetch",
            success: function(response) {
              for (var i = 0; i < response.length; i++) {
                dataSource.push({
                  id: response[i].id,
                  name: response[i].title,
                  startDate: new Date(response[i].start),
                  endDate: new Date(response[i].end),
                  color: response[i].backgroundColor
                });
              }
              $("#calendar").data("calendar").setDataSource(dataSource);
            }
          });
          console.log('dataSource -- loaded');`



If something works please tell, if need it I can adjunt an examle of my code that is just showin events an for now is working well hope it does helps.
Good luck!

**Comment by Lazaaa** [comment]
I change JQ 2.2.3 and tested a simple code, but not working :(
```
$(function() {
    var currentYear = new Date().getFullYear();
    $('#calendar').calendar({
        minDate: new Date('2016-01-01'),
        disabledWeekDays: [0,7],
        style: 'border',
        yearChanged: function(e) {
          e.preventRendering = true;
          var dataSource=[]; 
          $.ajax({ //get year holidays
            url: "szabiadatok.php", 
            type: "GET", 
            dataType: "json", 
            data: "type=fetch", 
            success: function(response) { 
              for (var i = 0; i < response.length; i++) { 
                dataSource.push({ 
                  id: response[i].id, 
                  name: response[i].title, 
                  startDate: new Date(response[i].start), 
                  endDate: new Date(response[i].end), 
                  color: response[i].backgroundColor }); 
                } 
              $("#calendar").data("calendar").setDataSource(dataSource); 
            } 
          }); 
          console.log('dataSource -- loaded');
          console.log(dataSource);
        },
        allowOverlap: true
    });
});
```
![capture](https://cloud.githubusercontent.com/assets/8706514/21427946/b35efa86-c857-11e6-8589-fd43eeb1768a.JPG)

**Comment by William-H-M** [comment]
Ok, I still don't figure out why it's happening but let's do this I'll give you my example is quite simple my data is from my database, I do not use ajax and I do not use year change for show data to other years I just load it all at once and i'll add the script of yearcalendar i'm using, if with this simple example doesn't work then I don't know what happend, now if you don't have data from database take this as datasource that is an option.

Hope it helps, because this is weird that you rrender is not working after all with the changes suggested worked formost of us. BTW refer to #49 He does the same for ajax datasource and maybe something can work for you too.

DataSource Option from calendar:

`$('#calendar').calendar({ ,
        dataSource: [
            {
                id: 0,
                name: 'Google I/O',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 4, 28),
                endDate: new Date(currentYear, 4, 29)
            },
            {
                id: 1,
                name: 'Microsoft Convergence',
                location: 'New Orleans, LA',
                startDate: new Date(currentYear, 2, 16),
                endDate: new Date(currentYear, 2, 19)
            },
            {
                id: 2,
                name: 'Microsoft Build Developer Conference',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 3, 29),
                endDate: new Date(currentYear, 4, 1)
            },
            {
                id: 3,
                name: 'Apple Special Event',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 8, 1),
                endDate: new Date(currentYear, 8, 1)
            },
            {
                id: 4,
                name: 'Apple Keynote',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 8, 9),
                endDate: new Date(currentYear, 8, 9)
            },
            {
                id: 5,
                name: 'Chrome Developer Summit',
                location: 'Mountain View, CA',
                startDate: new Date(currentYear, 10, 17),
                endDate: new Date(currentYear, 10, 18)
            },
            {
                id: 6,
                name: 'F8 2015',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 2, 25),
                endDate: new Date(currentYear, 2, 26)
            },
            {
                id: 7,
                name: 'Yahoo Mobile Developer Conference',
                location: 'New York',
                startDate: new Date(currentYear, 7, 25),
                endDate: new Date(currentYear, 7, 26)
            },
            {
                id: 8,
                name: 'Android Developer Conference',
                location: 'Santa Clara, CA',
                startDate: new Date(currentYear, 11, 1),
                endDate: new Date(currentYear, 11, 4)
            },
            {
                id: 9,
                name: 'LA Tech Summit',
                location: 'Los Angeles, CA',
                startDate: new Date(currentYear, 10, 17),
                endDate: new Date(currentYear, 10, 17)
            }
        ]});`

[Sample.txt](https://github.com/Paul-DS/bootstrap-year-calendar/files/669026/Sample.txt)

[script YC.txt](https://github.com/Paul-DS/bootstrap-year-calendar/files/669030/script.YC.txt)

**Comment by Lazaaa** [comment]
I do not know what could be the problem, just I know that if 31 days of the month will be the sixth series, it was not ready in the box-shadow that day.

**Comment by William-H-M** [comment]
Yeah I experienced the same Issue and with the refereces i gave solved it, but tell me with the try example i gave was the same or at least something changed?

**Comment by Lazaaa** [comment]
I think I found something, this is date conversion problem, Try it:
```
dataSource: [
      {
                id: 1,
                name: 'Microsoft Convergence',
                location: 'New Orleans, LA',
                startDate: new Date("October 31, 2016 11:13:00"),
                endDate: new Date("October 31, 2016 11:13:00")
            }],
```

this not showing in calendar, but mouseOnDay working. If u change startDate to "October 30, 2016 11:13:00" working correctly.

but u change 
```
dataSource: [
      {
                id: 1,
                name: 'Microsoft Convergence',
                location: 'New Orleans, LA',
                startDate: new Date(2016, 9, 31),
                endDate: new Date(2016, 9, 31)
            }],
```
working correctly too.

i don't know why, but i think this is a problem.

**Comment by William-H-M** [comment]
Well I thought I mention that before but on other issue #78 more exactly [here ](https://github.com/Paul-DS/bootstrap-year-calendar/issues/78#issuecomment-267609374) as you see on the image the time is given as 00:00:00 So looks like I gave you my old code, so with the code that you have to startDate and endDate just pass the date as simple as possible; and take maybe as reference his comment solution probably that would help too. If anything else happen lets check again after all code in the 90% of time is test and guessing to solve everything.
Good luck!

**Comment by Lazaaa** [comment]
ok, i finded solution, working fine.

**Comment by William-H-M** [comment]
Great Can you post it here? Just in case someone else have your problem in future and then please close this issue.

And I wish you a really happy and great Merry Christmas and Happy New Year too :)

**Comment by Lazaaa** [comment]
sure always use new Date(2016, 9, 31) format. Another date format is wrong way.
