### ISSUE TITLE
print calendar

### ISSUE THREAD

**Issue by IvanViana** [Paul-DS/bootstrap-year-calendar#83]
how i print the calendar with background colors?
the style in mode border or background not is printed.

**Comment by Paul-DS** [comment]
I'll need more information to help you. Can you share your code used for the calendar initialization in the first time ? And maybe describe a bit more the problem.

**Comment by IvanViana** [comment]
in the screen mode is show, but not in print mode.


` $('#calendar').calendar({ 
		enableContextMenu: true,
        enableRangeSelection: true,
		style:'background',
		
     dataSource:  <?php print $final; ?>,
		
		mouseOnDay: function(e) {
          	if(e.events.length > 0) {
				var y ;
				var content = "";
				for(y in e.events) {
				 					
								
		   content += '<div class="event-tooltip-content">'
                    + '<div class="event-name" style="color:' + e.events[(y)].color + '">' + e.events[(y)].name + '</div>'
                    + '<div class="event-location">' + e.events[(y)].location  + '</div>'
                    + '</div>';
                
				
                }
	
		
		 		$(e.element).popover({ 
                    trigger: 'manual',
                    container: 'body',
                    html:true,
                    content: content
                });
                
                $(e.element).popover('show');
  
			}
		
		
        },
		  mouseOutDay: function(e) {
            if(e.events.length > 0) {
                $(e.element).popover('hide');
            }
        },
        dayContextMenu: function(e) {
            $(e.element).popover('hide');
        },
		 
		
      
        
		 
    });
    
	 $('#calendar').data('calendar').setYear(<?php echo [ue_ano];?>);`
