### ISSUE TITLE
Fails to render events (border style) if Array prototype have been extended

### ISSUE THREAD

**Issue by paulwiik** [Paul-DS/bootstrap-year-calendar#84]
"_renderDataSourceDay" should check if events.hasOwnProperty(i), like this:
...
for(var i in events)
{
	if (events.hasOwnProperty(i)){
		if(boxShadow != '') {
			boxShadow += ",";
		}
		boxShadow += 'inset 0 -' + (parseInt(i) + 1) * weight + 'px 0 0 ' + events[i].color;
	}
}

...
In my case, another library had extended Array.prototype with a remove method, and it ended up with the calendar not displaying all Events.

**Comment by Paul-DS** [comment]
Hi,

Sorry for the late answer. The problem should now be fixed, I replaced all the "for" loops in the code (see commit 709c3bea2d79c8eeb7a178f744d112f059eaeb7f)

**Comment by paulwiik** [comment]
Thanks for fixing, and I'm sorry for being late in closing this issue (not familiar with Github, so I wasn't aware I needed to close it).
