### ISSUE TITLE
Ukrainian translation for calendar

### ISSUE THREAD

**Issue by WladKo** [Paul-DS/bootstrap-year-calendar#94]
Dear Paul,

Thanks for a great calendar, I use it at wordpress theme.
Here is Ukrainian translation, I suppose it will be useful.
Best regards

/**
 * Ukrainian translation for bootstrap-year-calendar
 * by Vadym Korolyuk
 */
 
;(function($){
	$.fn.calendar.dates['uk'] = {
		days: ["Неділя", "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця", "Субота"],
		daysShort: ["Нед", "Пон", "Вів", "Сер", "Чет", "Птн", "Суб"],
		daysMin: ["Нд", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
		months: ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень","Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
		monthsShort: ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис","Гру"],
		weekShort: 'н',
		weekStart: 1
	};
}(jQuery));

**Comment by Paul-DS** [comment]
Implemented in commit 53f9e9a1b308c4cdad14fcf5bf03419d738f6a4f

Thanks !
