### ISSUE TITLE
Render only the event on a single day

### ISSUE THREAD

**Issue by principe101** [Paul-DS/bootstrap-year-calendar#96]
Hi,
i need to render only the event on a single day using clickDay.

The code is:

`clickDay: function(e) {`
`  if(e.events.length == 0) `
`  {`
`      e.events.push({`
`          startDate: new Date(e.date),`
`	  endDate: new Date(e.date),`
`	  name: 'Ferie',`
`	  location: 'Richiesto',`
`	  color: '#f39c12'`
`       });`
`  }`
`  else`
`  {`
`      alert("OK");`
`  }`
`}`

On the first click i push new event in the events array, but without refresh of entire calendar on the next click e.events.length is still 0. Also the color of day are unchanged.

Can you help me?

Regards,
Leonardo

**Comment by Paul-DS** [comment]
The event list contained in the event parameters is just an extract of the calendar data source. This list is not linked to the real datasource.

If you want to add the event, just use the **addEvent** method of the calendar:
```
clickDay: function(e) {
	if(e.events.length == 0)
	{
		$('#calendar').data('calendar').addEvent({
			startDate: new Date(e.date),
			endDate: new Date(e.date),
			name: 'Ferie',
			location: 'Richiesto',
			color: '#f39c12'
		});
	}
	else
	{
		alert("OK");
	}
}
```
