### ISSUE TITLE
Will there be a port to Vue 2.0?

### ISSUE THREAD

**Issue by frankleja** [Paul-DS/bootstrap-year-calendar#97]
I'm working with Vue 2.0 (started) and looked for a year style calendar. I found your beautiful calendar and wondering if you/someone might port this component to Vue 2.0?

**Comment by imolitor** [comment]
plus 1

**Comment by isfreedom** [comment]
+1

**Comment by Paul-DS** [comment]
You can now use the Vue.js wrapper of the calendar: https://github.com/year-calendar/v-year-calendar
