### ISSUE TITLE
Doesn't works dataSource.push()

### ISSUE THREAD

**Issue by Anabantha** [Paul-DS/bootstrap-year-calendar#98]
Hello,
I'm trying to include Bootstrap-year-Calendar in my website project, but doesn't works. I change several items and this is the modified script in the functions of edit and save:

`function editEvent(event) {
    $('#event-modal input[name="event-index"]').val(event ? event.id : '');
   	$('#select_id option:selected[name="event-name"]').text(event ? event.name : '');
    $('#event-modal input[name="event-start-date"]').datepicker('update', event ? event.startDate : '');
    $('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.endDate : '');
    $('#event-modal').modal();
}`

`function saveEvent() {
    var event = {
        id: $('#event-modal input[name="event-index"]').val(),
        name: $('#select_id option:selected[name="event-name"]').text(),
        startDate: $('#event-modal input[name="event-start-date"]').datepicker('getDate'),
        endDate: $('#event-modal input[name="event-end-date"]').datepicker('getDate')
    }
    var dataSource = $('#calendar').data('calendar').getDataSource();
    if(event.id) {
        for(var i in dataSource) {
        		console.log("aqui empieza el if de dataSource");
            if(dataSource[i].id == event.id) {
                dataSource[i].name = event.name;
                dataSource[i].startDate = event.startDate;
                dataSource[i].endDate = event.endDate;
            }
        }
    }
    else
    {
        var newId = 0;
        for(var i in dataSource) {
            if(dataSource[i].id > newId) {
                newId = dataSource[i].id;
            }
        }
        newId++;
        event.id = newId;
        console.log(event);
        dataSource.push();
    }`

And this is the console error: SCRIPT5007: Unable to get property 'push' of undefined or null reference.

If I use `dataSource.push(event)` the result is the same. I did the test with `console.log(dataSource)` and its empty. What's wrong?

Regards.
![screen1](https://cloud.githubusercontent.com/assets/7441510/22833282/ecb662ba-ef76-11e6-8b18-a908ea34d54f.png)
![screen2](https://cloud.githubusercontent.com/assets/7441510/22833283/ecbe2cac-ef76-11e6-841b-9478aee09af2.png)
![screen3](https://cloud.githubusercontent.com/assets/7441510/22833287/ecf7a2a2-ef76-11e6-9769-968850798c1e.png)
![screen4](https://cloud.githubusercontent.com/assets/7441510/22833286/ecf6c9a4-ef76-11e6-9641-0755830bd39b.png)
![screen5](https://cloud.githubusercontent.com/assets/7441510/22833284/ecf4cad2-ef76-11e6-8e2e-23fff99482e1.png)
![screen6](https://cloud.githubusercontent.com/assets/7441510/22833285/ecf4e9ae-ef76-11e6-85ce-f965d99c8b3c.png)
![screen7](https://cloud.githubusercontent.com/assets/7441510/22833288/ecf9f282-ef76-11e6-843c-f5e253352dac.png)
![screen8](https://cloud.githubusercontent.com/assets/7441510/22833289/ecfc6bac-ef76-11e6-9563-6430e9dbf452.png)

**Comment by William-H-M** [comment]
That's quite weird you have as is need it can you please just copy the code given on the [example page](http://www.bootstrap-year-calendar.com/#Examples/Full%20example) maybe is or because some bad writing, other problem that can possible be is
1) Problem with some library like JQuery version that's is too old for the function or name changed
2) If you're using IE9 or down usually it breaks the scripts so try with other browser.

Suerte!

**Comment by Anabantha** [comment]
I'd already thought about those three possibilities but, the mistakes continue. In fact, I coded the calendar alone, without any styles that didn't belong it and still doesn't works properly. So, I don't know what could be the problem, if everything is supposed to be correct.

**Comment by toretronic** [comment]
Hi

And trying something like this?
[#86](https://github.com/Paul-DS/bootstrap-year-calendar/issues/86)

Suerte!

**Comment by Anabantha** [comment]
I already found the error, could not add events because I had eliminated the events that the example has by default (dataSource) and caused error in the dataSource.push (). Now I can add events, thanks.

I admit that I'm new to programming and everything is new to me. I have other doubts, if they are so kind to help me, I would thank you very much. They are the following points:

Block the last days and only be availables from the present day onwards.
Show MySQL data up to the calendar with Ajax and PHP. (holidays for example).
And finally send all the events in an array with Ajax and PHP to MySQL

I have seen tutorials but I have not been able to understand them very well and with others errors appear again and again.

This is my code for a moment:


![request1](https://cloud.githubusercontent.com/assets/7441510/23180657/ba122bf4-f837-11e6-9f30-2021cbe8813e.png)
![request2](https://cloud.githubusercontent.com/assets/7441510/23180656/ba1230c2-f837-11e6-8916-eff589e2cc78.png)
![request3](https://cloud.githubusercontent.com/assets/7441510/23180658/ba1316fe-f837-11e6-8b35-d60b1e8ffae3.png)
![request4](https://cloud.githubusercontent.com/assets/7441510/23180655/ba121b8c-f837-11e6-8392-da870d2e77bd.png)
![request5](https://cloud.githubusercontent.com/assets/7441510/23180659/ba152bb0-f837-11e6-9a6a-0391edefff07.png)
