### ISSUE TITLE
Rendering months full width of Div

### ISSUE THREAD

**Issue by martin0852** [Paul-DS/bootstrap-year-calendar#99]
Hi, 

Awesome project by the way! 

I'm having an issue rendering the calendar where the months are taking the full width of the div. This results in the calendar being a list of 12 months instead of the year view like on the examples.
Below is the example:
![image](https://cloud.githubusercontent.com/assets/12892509/22857476/a463b74c-f09d-11e6-8ada-5d47ce3fcdb3.png)

I am using the latest version on the site V.1.1.0

Any ideas what's happening here?

I've checked my own CSS and there are no styles imposing themselves on the calendar.

Thanks, M

**Comment by martin0852** [comment]
Sorry - the issue was a roque css width value - my bad!

**Comment by William-H-M** [comment]
To be honoest doesn't look that bad can you post what you did to do that maybe someone else, including myself, would need it for a crazy requirement from a crazy client

**Comment by martin0852** [comment]
Believe it or not but I had table width set to 96% 🙃
